import assert from "node:assert/strict";
import { DomainError } from "@whox/contracts";
import { describe, it } from "node:test";
import { InMemoryPushProvider, MemoryNotificationRepository, NotificationProcessor, NotificationQuietHoursError, type PushProvider, validateNotificationPayload } from "../src/index.js";

const base={notificationType:"proposal_ready",priority:"normal",title:"Proposal ready",privateBody:"Review 5 shares of AAPL at $200.",publicBody:"Open Metis to review.",occurredAt:"2026-08-01T02:00:00.000Z",notificationIdempotencyKey:"notification-key-1"} as const;
describe("notification safety",()=>{
  it("accepts exactly the registered iOS route vocabulary",()=>{for(const deepLink of ["metis://dashboard","metis://proposals","metis://active-agent","metis://risk","metis://risk/pause","metis://activity/event-1","metis://agent/agent-1","metis://position/position-1"])assert.equal(validateNotificationPayload({...base,deepLink}).deepLink,deepLink);for(const deepLink of ["whox-treasury://dashboard","metis://order/1","https://evil.example"])assert.throws(()=>validateNotificationPayload({...base,deepLink}),/route allowlist/);});
  it("uses the public body when detailed previews are disabled",async()=>{const provider=new InMemoryPushProvider();const processor=new NotificationProcessor(new MemoryNotificationRepository(),provider);await processor.process("user-1",base,"2026-08-01T14:00:00.000Z");assert.equal(provider.deliveries[0]?.body,base.publicBody);assert.equal(provider.deliveries[0]?.body.includes("AAPL"),false);});
  it("defers summaries during quiet hours but not enabled time-sensitive risk alerts",async()=>{const quiet={startMinute:22*60,endMinute:7*60,utcOffsetMinutes:0};const processor=new NotificationProcessor(new MemoryNotificationRepository({detailedPreviewsEnabled:false,criticalNotificationsEnabled:true,quietHours:quiet}),new InMemoryPushProvider());await assert.rejects(processor.process("user-1",base,"2026-08-01T23:00:00.000Z"),(error:unknown)=>error instanceof NotificationQuietHoursError&&error.availableAt==="2026-08-02T07:00:00.000Z");await assert.doesNotReject(processor.process("user-1",{...base,notificationType:"risk_daily_loss",priority:"time_sensitive",notificationIdempotencyKey:"notification-risk-1"},"2026-08-01T23:00:00.000Z"));});
  it("ignores queue-supplied privacy and quiet-hours overrides",async()=>{const provider=new InMemoryPushProvider();const processor=new NotificationProcessor(new MemoryNotificationRepository(),provider);await processor.process("user-1",{...base,detailedPreviewsEnabled:true,criticalNotificationsEnabled:true,quietHours:{startMinute:0,endMinute:1439,utcOffsetMinutes:0}},"2026-08-01T14:00:00.000Z");assert.equal(provider.deliveries[0]?.body,base.publicBody);});
  it("acknowledges a delivered replay without sending a duplicate push",async()=>{const provider=new InMemoryPushProvider();const processor=new NotificationProcessor(new MemoryNotificationRepository(),provider);const first=await processor.process("user-1",base,"2026-08-01T14:00:00.000Z");const replay=await processor.process("user-1",base,"2026-08-01T14:01:00.000Z");assert.equal(provider.deliveries.length,1);assert.equal(replay.id,first.id);assert.equal(replay.deliveredAt,first.deliveredAt);});
  it("records a provider failure and permits a later durable retry",async()=>{let attempt=0;const provider:PushProvider={async deliver(){attempt+=1;if(attempt===1)throw new DomainError("APNS_DELIVERY_FAILED","temporary",503);}};const processor=new NotificationProcessor(new MemoryNotificationRepository(),provider);await assert.rejects(processor.process("user-1",base,"2026-08-01T14:00:00.000Z"),/temporary/);await assert.doesNotReject(processor.process("user-1",base,"2026-08-01T14:01:00.000Z"));assert.equal(attempt,2);});
});
