import assert from "node:assert/strict";
import { describe, it } from "node:test";
import type { Entitlements, ReleaseGates, RiskPolicy, TradeProposal } from "@whox/contracts";
import { createProposalAggregate, InMemoryProposalStore, type ProposalAggregate, type TransitionCommand } from "@whox/agent-orchestrator";
import type { RiskContext } from "@whox/risk-schemas";
import { DEMO_EQUITY_ENTITLEMENTS, DEMO_EQUITY_PROPOSAL, DEMO_RISK_POLICY } from "@whox/test-fixtures";
import type { BrokerGateway, BrokerReview, BrokerSubmission, PlacementReconciliation } from "../src/brokers.js";
import { ExecutionWorker, type ExecutionAuthorization } from "../src/index.js";

const now="2026-08-01T14:00:02.000Z";
const gates:ReleaseGates=Object.freeze({LIVE_TRADING_ENABLED:false,ROBINHOOD_PRODUCTION_APPROVED:false,LEGAL_DOCUMENTS_APPROVED:false,ADVISORY_COMPLIANCE_APPROVED:false,APP_STORE_FINANCIAL_ENTITY_APPROVED:false,OPTIONS_LIVE_TRADING_ENABLED:false,AUTONOMOUS_MODE_ENABLED:false});

const context:RiskContext={now,releaseGates:gates,userStatus:"active",currentLegalConsents:true,entitlements:DEMO_EQUITY_ENTITLEMENTS,accountConnectionHealthy:true,verifiedAgenticAccountId:DEMO_EQUITY_PROPOSAL.accountId,strategyEnabled:true,agentVersionEnabled:true,tradingPermission:true,marketSession:"open",criticalServicesHealthy:true,securityHalt:false,accountValue:10_000,buyingPower:5_000,reservedBuyingPower:0,currentAllocatedValue:1_000,currentPositionValue:0,currentSectorValue:0,openPositionCount:1,dailyLoss:0,drawdownRatio:0,agentAllocatedValue:0,agentAllocationLimit:5_000,otherAgentReservations:0,duplicateProposal:false,duplicateOpenOrder:false,symbolSector:"Technology",tradable:true,fractionalSupported:true,liquiditySufficient:true,volatilityHalt:false,tradingHalt:false,corporateActionRestricted:false,earningsWindow:false,cooldownActive:false,tradesToday:0,turnoverToday:0,accountSnapshotTimestamp:now,quotePrice:200,expectedExecutionPrice:200,brokerWarningSeverity:"none",approvalExpiresAt:"2026-08-01T14:05:00.000Z"};

function authorization(proposal:TradeProposal,overrides:Partial<ExecutionAuthorization>={}):ExecutionAuthorization{return Object.freeze({verifiedBy:"persistent-execution-store",ownerUserId:proposal.userId,verifiedAccountId:proposal.accountId,policyId:DEMO_RISK_POLICY.policyId,policyVersion:DEMO_RISK_POLICY.version,approvalMode:proposal.requiredApprovalMode,authorizationKind:"authenticated_user",authorizationReference:"approval-request-1",placementAuthorized:true,entitlements:DEMO_EQUITY_ENTITLEMENTS,releaseGates:gates,userStatus:"active",strategyEnabled:true,agentVersionEnabled:true,accountConnectionHealthy:true,tradingPermission:true,...overrides});}

function transition(toStatus:TransitionCommand["toStatus"],actorType:TransitionCommand["actorType"],version:number,extra:Partial<TransitionCommand>={}):TransitionCommand{return {toStatus,actorType,actorId:actorType==="user"?DEMO_EQUITY_PROPOSAL.userId:"test-worker",reasonCode:"TEST",correlationId:"execution-state-test",idempotencyKey:`prepare-${version}-${toStatus}`,occurredAt:"2026-08-01T14:00:01.000Z",...extra};}

async function approvedStore(proposal:TradeProposal=DEMO_EQUITY_PROPOSAL):Promise<{readonly store:InMemoryProposalStore;readonly aggregate:ProposalAggregate}>{const store=new InMemoryProposalStore();let aggregate=await store.create(proposal,"approved-create-key","2026-08-01T14:00:00.000Z");for(const [status,actor] of [["ANALYZED","worker"],["SCHEMA_VALIDATED","worker"],["RISK_CHECKED","worker"],["BROKER_REVIEWED","broker"],["AWAITING_USER_APPROVAL","worker"]] as const)aggregate=await store.transition(proposal.proposalId,aggregate.version,transition(status,actor,aggregate.version));aggregate=await store.transition(proposal.proposalId,aggregate.version,transition("APPROVED","user",aggregate.version,{actorId:proposal.userId,userAuthentication:{authenticatedUserId:proposal.userId,authenticationContextId:"auth-context-1",authenticatedAt:"2026-08-01T14:00:00.000Z"}}));return {store,aggregate};}

class TestBroker implements BrokerGateway{
  public readonly environment="demo" as const;public placeCalls=0;public reconcileCalls=0;
  public constructor(private readonly placement:"throw"|"filled"="filled",private readonly reconciliation:PlacementReconciliation={resolution:"not_found"}){}
  public async review(proposal:TradeProposal,at:string):Promise<BrokerReview>{return Object.freeze({reviewId:"review-1",accountId:proposal.accountId,proposalId:proposal.proposalId,warnings:Object.freeze([]),reviewedAt:at});}
  public async place(_proposal:TradeProposal,_review:BrokerReview,_key:string,at:string):Promise<BrokerSubmission>{this.placeCalls+=1;if(this.placement==="throw")throw new Error("simulated placement timeout");return Object.freeze({brokerOrderId:"broker-order-1",status:"filled",submittedAt:at,filledQuantity:5,averageFillPrice:200});}
  public async reconcilePlacement():Promise<PlacementReconciliation>{this.reconcileCalls+=1;return this.reconciliation;}
  public async cancel():Promise<never>{throw new Error("not used");}
}

describe("execution authorization and recovery",()=>{
  it("rejects a forged Observe-mode aggregate before broker activity",async()=>{const proposal={...DEMO_EQUITY_PROPOSAL,requiredApprovalMode:"observe" as const};const aggregate={...createProposalAggregate(proposal,"2026-08-01T14:00:00.000Z"),status:"APPROVED" as const,version:6};const broker=new TestBroker();const worker=new ExecutionWorker(new InMemoryProposalStore(),broker);await assert.rejects(worker.submitApproved({aggregate,policy:DEMO_RISK_POLICY,riskContext:{...context},authorization:authorization(proposal,{approvalMode:"observe"}),idempotencyKey:"observe-execution",correlationId:"observe",now}),(error:unknown)=>typeof error==="object"&&error!==null&&"code" in error&&error.code==="OBSERVE_MODE_EXECUTION_FORBIDDEN");assert.equal(broker.placeCalls,0);});
  it("rejects a risk policy belonging to another user",async()=>{const {store,aggregate}=await approvedStore();const broker=new TestBroker();const worker=new ExecutionWorker(store,broker);const wrongPolicy={...DEMO_RISK_POLICY,userId:"00000000-0000-4000-8000-000000000099"} satisfies RiskPolicy;await assert.rejects(worker.submitApproved({aggregate,policy:wrongPolicy,riskContext:context,authorization:authorization(DEMO_EQUITY_PROPOSAL),idempotencyKey:"wrong-policy-user",correlationId:"policy",now}),(error:unknown)=>typeof error==="object"&&error!==null&&"code" in error&&error.code==="EXECUTION_POLICY_BINDING_INVALID");assert.equal(broker.placeCalls,0);});
  it("records an unknown placement as RECONCILIATION_ERROR, never REJECTED",async()=>{const {store,aggregate}=await approvedStore();const broker=new TestBroker("throw");const worker=new ExecutionWorker(store,broker);await assert.rejects(worker.submitApproved({aggregate,policy:DEMO_RISK_POLICY,riskContext:context,authorization:authorization(DEMO_EQUITY_PROPOSAL),idempotencyKey:"ambiguous-placement",correlationId:"ambiguous",now}),(error:unknown)=>typeof error==="object"&&error!==null&&"code" in error&&error.code==="PLACEMENT_OUTCOME_AMBIGUOUS");assert.equal((await store.get(aggregate.proposal.proposalId))?.status,"RECONCILIATION_ERROR");});
  it("reconciles after restart without blindly placing again",async()=>{const {store,aggregate}=await approvedStore();const first=new ExecutionWorker(store,new TestBroker("throw"));await assert.rejects(first.submitApproved({aggregate,policy:DEMO_RISK_POLICY,riskContext:context,authorization:authorization(DEMO_EQUITY_PROPOSAL),idempotencyKey:"restart-safe-key",correlationId:"restart",now}));const ambiguous=(await store.get(aggregate.proposal.proposalId))!;const submission:BrokerSubmission=Object.freeze({brokerOrderId:"recovered-order",status:"filled",submittedAt:now,filledQuantity:5,averageFillPrice:200});const review:BrokerReview=Object.freeze({reviewId:"recovered-review",accountId:aggregate.proposal.accountId,proposalId:aggregate.proposal.proposalId,warnings:Object.freeze([]),reviewedAt:now});const recoveredBroker=new TestBroker("filled",{resolution:"found",review,submission});const restarted=new ExecutionWorker(store,recoveredBroker);const outcome=await restarted.submitApproved({aggregate:ambiguous,policy:DEMO_RISK_POLICY,riskContext:context,authorization:authorization(DEMO_EQUITY_PROPOSAL,{placementAuthorized:false}),idempotencyKey:"restart-safe-key",correlationId:"restart",now:"2026-08-01T14:00:03.000Z"});assert.equal(outcome.aggregate.status,"FILLED");assert.equal(recoveredBroker.reconcileCalls,1);assert.equal(recoveredBroker.placeCalls,0);});
});
