import assert from "node:assert/strict";
import { describe, it } from "node:test";
import type { TradeProposal } from "@whox/contracts";
import { DEMO_EQUITY_PROPOSAL } from "@whox/test-fixtures";
import { PaperBroker } from "../src/brokers.js";
import { RobinhoodMcpBroker, type RobinhoodOrderArgumentMapper } from "../src/brokers.js";
import { McpStreamableHttpClient } from "../src/mcp-client.js";
import { TokenVault, type TokenKeyProvider } from "../src/token-vault.js";

describe("Paper broker execution",()=>{
  it("never fills a buy limit above the limit",async()=>{const broker=new PaperBroker("demo");const proposal={...DEMO_EQUITY_PROPOSAL,side:"buy" as const,limitPrice:200};const review=await broker.review(proposal,"2026-08-01T14:00:00Z");const result=await broker.place(proposal,review,"paper-buy-limit","2026-08-01T14:00:01Z");assert.equal(result.averageFillPrice,200);});
  it("never fills a sell limit below the limit",async()=>{const broker=new PaperBroker("demo");const proposal={...DEMO_EQUITY_PROPOSAL,side:"sell" as const,limitPrice:200};const review=await broker.review(proposal,"2026-08-01T14:00:00Z");const result=await broker.place(proposal,review,"paper-sell-limit","2026-08-01T14:00:01Z");assert.equal(result.averageFillPrice,200);});
  it("rejects non-finite numeric input before deriving a price",async()=>{const broker=new PaperBroker("demo");const proposal={...DEMO_EQUITY_PROPOSAL,quantity:Number.NaN} as unknown as TradeProposal;const review=await broker.review(proposal,"2026-08-01T14:00:00Z");await assert.rejects(broker.place(proposal,review,"paper-invalid-number","2026-08-01T14:00:01Z"),/finite and positive/);});
  it("fails Paper review closed without approved persisted market data",async()=>{const broker=new PaperBroker("paper");const proposal={...DEMO_EQUITY_PROPOSAL,environment:"paper" as const};await assert.rejects(broker.review(proposal,"2026-08-01T14:00:00Z"),(error:unknown)=>typeof error==="object"&&error!==null&&"code" in error&&error.code==="PAPER_MARKET_DATA_REQUIRED");});
  it("prices a Paper fill from its approved quote rather than the proposal limit",async()=>{const broker=new PaperBroker("paper");const proposal={...DEMO_EQUITY_PROPOSAL,environment:"paper" as const,limitPrice:205};const marketQuote={verifiedBy:"approved-market-data-store" as const,symbol:"AAPL",bid:200,ask:201,last:200.5,sourceTimestamp:"2026-08-01T14:00:00Z",provider:"approved-provider"};const review=await broker.review(proposal,"2026-08-01T14:00:01Z",{marketQuote});const result=await broker.place(proposal,review,"paper-approved-quote","2026-08-01T14:00:01Z");assert.equal(result.averageFillPrice,201.0402);assert.notEqual(result.averageFillPrice,proposal.limitPrice);});
});

describe("live cancellation routing",()=>{
  it("uses the persisted order instrument when both cancel tools are discovered",async()=>{const called:string[]=[];const fetcher:typeof fetch=async(_input,init)=>{const body=JSON.parse(String(init?.body)) as {id:number;method:string;params?:{name?:string}};if(body.method==="tools/list")return new Response(JSON.stringify({jsonrpc:"2.0",id:body.id,result:{tools:["place_equity_order","cancel_equity_order","cancel_option_order"].map((name)=>({name,inputSchema:{type:"object"}}))}}),{status:200,headers:{"content-type":"application/json"}});called.push(body.params?.name??"");return new Response(JSON.stringify({jsonrpc:"2.0",id:body.id,result:{content:[]}}),{status:200,headers:{"content-type":"application/json"}});};const client=new McpStreamableHttpClient({endpoint:new URL("https://broker.example/mcp"),accessToken:async()=>"access-token",fetcher});await client.initialize();await client.discoverTools();const mapper:RobinhoodOrderArgumentMapper={approvedMappingVersion:"test-approved",mapReview:()=>({}),parseReview:(_result,proposal,at)=>({reviewId:"review-1",accountId:proposal.accountId,proposalId:proposal.proposalId,warnings:[],reviewedAt:at}),mapPlace:()=>({}),parsePlacement:(_result,_proposal,at)=>({brokerOrderId:"broker-order-1",status:"submitted",submittedAt:at,filledQuantity:0}),mapCancel:()=>({}),parseCancellation:(_result,brokerOrderId,at)=>({brokerOrderId,canceled:true,status:"canceled",occurredAt:at})};const gates={LIVE_TRADING_ENABLED:true,ROBINHOOD_PRODUCTION_APPROVED:true,LEGAL_DOCUMENTS_APPROVED:true,ADVISORY_COMPLIANCE_APPROVED:true,APP_STORE_FINANCIAL_ENTITY_APPROVED:true,OPTIONS_LIVE_TRADING_ENABLED:true,AUTONOMOUS_MODE_ENABLED:true} as const;const proposal={...DEMO_EQUITY_PROPOSAL,environment:"live" as const};const broker=new RobinhoodMcpBroker(client,proposal.accountId,gates,mapper);const review={reviewId:"review-1",accountId:proposal.accountId,proposalId:proposal.proposalId,warnings:[],reviewedAt:"2026-08-01T14:00:00Z"};await broker.place(proposal,review,"placement-key","2026-08-01T14:00:00Z");await broker.cancel("broker-order-1","cancel-key","2026-08-01T14:01:00Z");assert.deepEqual(called,["place_equity_order","cancel_equity_order"]);});
});

class ObservedKeyProvider implements TokenKeyProvider {public readonly key:Buffer;public constructor(length=32){this.key=Buffer.alloc(length,7);}public async currentKeyId():Promise<string>{return "test-key";}public async getEncryptionKey():Promise<Buffer>{return this.key;}}
describe("Token vault memory hygiene",()=>{
  it("wipes provider key material after successful sealing",async()=>{const provider=new ObservedKeyProvider();const vault=new TokenVault(provider);const envelope=await vault.seal("user-1","connection-1",{accessToken:"secret",tokenType:"Bearer",expiresAt:"2026-08-01T15:00:00Z"},"2026-08-01T14:00:00Z");assert.equal(provider.key.every((byte)=>byte===0),true);assert.notEqual(envelope.ciphertext,"");});
  it("wipes key material when cipher construction fails",async()=>{const provider=new ObservedKeyProvider(16);const vault=new TokenVault(provider);await assert.rejects(vault.seal("user-1","connection-1",{accessToken:"secret",tokenType:"Bearer",expiresAt:"2026-08-01T15:00:00Z"},"2026-08-01T14:00:00Z"));assert.equal(provider.key.every((byte)=>byte===0),true);});
});
