import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { InMemoryPendingAuthorizationStore, McpOAuthClient } from "../src/oauth.js";
import { McpStreamableHttpClient } from "../src/mcp-client.js";

const json=(value:unknown,status=200,headers:Record<string,string>={}):Response=>new Response(JSON.stringify(value),{status,headers:{"content-type":"application/json",...headers}});

describe("OAuth protected-resource flow",()=>{
  it("uses discovery fallbacks, PKCE/resource binding, refresh preservation, revocation, and one-time state",async()=>{const calls:{url:string;init?:RequestInit}[]=[];const resource="https://broker.example/mcp/trading";const fetcher:typeof fetch=async(input,init)=>{const url=String(input);calls.push({url,...(init===undefined?{}:{init})});if(url.endsWith("/.well-known/oauth-protected-resource/mcp/trading"))return json({resource,authorization_servers:["https://auth.example/issuer"],scopes_supported:["trade"]});if(url.includes("oauth-authorization-server"))return new Response("",{status:404});if(url.endsWith("/.well-known/openid-configuration/issuer"))return json({issuer:"https://auth.example/issuer",authorization_endpoint:"https://auth.example/authorize",token_endpoint:"https://auth.example/token",revocation_endpoint:"https://auth.example/revoke",response_types_supported:["code"],code_challenge_methods_supported:["S256"],authorization_response_iss_parameter_supported:true});if(url==="https://auth.example/token"){const body=String(init?.body);assert.match(body,/resource=https%3A%2F%2Fbroker\.example%2Fmcp%2Ftrading/);return body.includes("authorization_code")?json({access_token:"access-token-one",token_type:"Bearer",expires_in:300,refresh_token:"refresh-one"}):json({access_token:"access-token-two",token_type:"Bearer",expires_in:300});}if(url==="https://auth.example/revoke")return new Response(null,{status:200});throw new Error(`unexpected ${url}`);};const client=new McpOAuthClient(fetcher,new URL(resource),"client-1",new Set(["http://127.0.0.1:48123/callback"]),new InMemoryPendingAuthorizationStore());const discovery=await client.discover();const pending=await client.begin(discovery,{userId:"user-1",pairingId:"pairing-1",redirectUri:"http://127.0.0.1:48123/callback",now:"2026-08-01T14:00:00Z"});const authorization=new URL(pending.authorizationUrl);assert.equal(authorization.searchParams.get("code_challenge_method"),"S256");assert.equal(authorization.searchParams.get("resource"),resource);const exchanged=await client.exchange(discovery,{code:"code-1",state:pending.state,issuer:"https://auth.example/issuer",now:"2026-08-01T14:01:00Z"});assert.equal(exchanged.tokens.refreshToken,"refresh-one");await assert.rejects(client.exchange(discovery,{code:"code-1",state:pending.state,issuer:"https://auth.example/issuer",now:"2026-08-01T14:01:01Z"}),/state is invalid/);const refreshed=await client.refresh(discovery,exchanged.tokens,"2026-08-01T14:02:00Z");assert.equal(refreshed.refreshToken,"refresh-one");assert.equal(await client.revoke(discovery,refreshed.accessToken,"access_token"),true);assert.ok(calls.some((call)=>call.url.endsWith("openid-configuration/issuer")));});
});

describe("MCP protocol negotiation",()=>{
  it("uses the stateless 2026 protocol metadata and runtime tool schemas",async()=>{const requests:{headers:Headers;body:Record<string,unknown>}[]=[];const fetcher:typeof fetch=async(_input,init)=>{const headers=new Headers(init?.headers);const body=JSON.parse(String(init?.body)) as Record<string,unknown>;requests.push({headers,body});const id=body.id as number;if(body.method==="tools/list")return json({jsonrpc:"2.0",id,result:{tools:[{name:"review_equity_order",inputSchema:{type:"object",required:["accountId"],properties:{accountId:{type:"string","x-mcp-header":"Account"}},additionalProperties:false}}]}});return json({jsonrpc:"2.0",id,result:{content:[],isError:false}});};const client=new McpStreamableHttpClient({endpoint:new URL("https://broker.example/mcp"),accessToken:async()=>"access-token",fetcher});assert.equal((await client.initialize()).protocolVersion,"2026-07-28");await client.discoverTools();await client.callTool("review_equity_order",{accountId:"acct-1"});const call=requests.at(-1)!;assert.equal(call.headers.get("mcp-protocol-version"),"2026-07-28");assert.equal(call.headers.get("mcp-method"),"tools/call");assert.equal(call.headers.get("mcp-name"),"review_equity_order");assert.equal(call.headers.get("mcp-param-account"),"acct-1");const params=call.body.params as { _meta:Record<string,unknown>};assert.equal(params._meta["io.modelcontextprotocol/protocolVersion"],"2026-07-28");});
  it("falls back to the legacy initialize/session flow only after a rejected modern probe",async()=>{let step=0;const fetcher:typeof fetch=async(_input,init)=>{step+=1;const body=JSON.parse(String(init?.body)) as Record<string,unknown>;if(step===1)return json({jsonrpc:"2.0",id:body.id,error:{code:-32022,message:"version",data:{supported:["2025-11-25"]}}},400);if(body.method==="initialize")return json({jsonrpc:"2.0",id:body.id,result:{protocolVersion:"2025-11-25",capabilities:{tools:{}},serverInfo:{name:"legacy",version:"1"}}},200,{"mcp-session-id":"session-1"});if(body.method==="notifications/initialized")return new Response(null,{status:202});return json({jsonrpc:"2.0",id:body.id,result:{tools:[]}});};const client=new McpStreamableHttpClient({endpoint:new URL("https://broker.example/mcp"),accessToken:async()=>"access-token",fetcher});const initialized=await client.initialize();assert.equal(initialized.protocolVersion,"2025-11-25");assert.equal(initialized.sessionId,"session-1");assert.deepEqual(await client.discoverTools(),[]);});
});
