import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { randomUUID } from "node:crypto";
import { Pool } from "pg";
import { InMemoryCoordinationAdapter, InMemoryDurableJobQueue, PollingWorker, PostgresDurableJobQueue, assertAgentPipelineConfigured, combineAgentOrchestratorHealth } from "../src/index.js";

describe("agent pipeline startup",()=>{
  it("fails Paper until its persistent pipeline is configured and keeps Live locked",()=>{assert.throws(()=>assertAgentPipelineConfigured("paper"),(error:unknown)=>typeof error==="object"&&error!==null&&"code" in error&&error.code==="AGENT_PIPELINE_UNCONFIGURED");assert.doesNotThrow(()=>assertAgentPipelineConfigured("paper",true));assert.throws(()=>assertAgentPipelineConfigured("live",true),(error:unknown)=>typeof error==="object"&&error!==null&&"code" in error&&error.code==="AGENT_PIPELINE_UNCONFIGURED");assert.doesNotThrow(()=>assertAgentPipelineConfigured("demo"));});
  it("makes scheduler lag visible as top-level degraded health",()=>{const worker={name:"agent-orchestrator",state:"ready" as const,workerId:"worker",processed:1,failed:0,lastHeartbeat:new Date().toISOString()};const scheduler={state:"lagging" as const,lastTickAt:new Date().toISOString(),lastSuccessAt:new Date().toISOString(),lockContentions:0,evaluatedAgents:1,dueAgents:1,refreshJobsEnqueued:0,researchJobsEnqueued:0,agentRunsEnqueued:0,researchBlockedAgents:0,backpressureBlockedAgents:0,quoteBlockedAgents:1,otherBlockedAgents:0,maxSchedulingLagSeconds:301,lagAlertThresholdSeconds:300};const health=combineAgentOrchestratorHealth(worker,scheduler);assert.equal(health.state,"degraded");assert.equal(health.scheduler?.state,"lagging");});
});

describe("coordination safety",()=>{
  it("releases only the current lock owner and expires stale owners",async()=>{let now=1_000;const coordination=new InMemoryCoordinationAdapter(()=>now);const first=await coordination.acquireLock("proposal:1",500);assert.ok(first);assert.equal(await coordination.acquireLock("proposal:1",500),undefined);assert.equal(await coordination.releaseLock({...first,ownerToken:"not-owner"}),false);now=1_501;const second=await coordination.acquireLock("proposal:1",500);assert.ok(second);assert.notEqual(second.ownerToken,first.ownerToken);assert.equal(await coordination.releaseLock(first),false);assert.equal(await coordination.releaseLock(second),true);});
  it("coordinates sliding rate limits and expiring cache",async()=>{let now=2_000;const coordination=new InMemoryCoordinationAdapter(()=>now);assert.equal((await coordination.consumeRateLimit("login",2,1_000,now)).allowed,true);assert.equal((await coordination.consumeRateLimit("login",2,1_000,now)).allowed,true);assert.equal((await coordination.consumeRateLimit("login",2,1_000,now)).allowed,false);await coordination.setJson("capabilities",{version:1},500);assert.deepEqual(await coordination.getJson("capabilities"),{version:1});now=2_501;assert.equal(await coordination.getJson("capabilities"),undefined);});
});

describe("durable worker semantics",()=>{
  it("binds idempotency keys to payloads and completes exactly one claimed job",async()=>{const queue=new InMemoryDurableJobQueue();const command={queueName:"agent-runs",jobType:"agent_run",payload:{userAgentId:"agent-1"},idempotencyKey:"agent-job-key"} as const;const id=await queue.enqueue(command);assert.equal(await queue.enqueue(command),id);await assert.rejects(queue.enqueue({...command,payload:{userAgentId:"agent-2"}}),/different payload/);let handled=0;const worker=new PollingWorker("test",queue,"agent-runs",async()=>{handled+=1;},10,1_000,"worker-1");assert.equal(await worker.runOnce(new AbortController().signal),true);assert.equal(await worker.runOnce(new AbortController().signal),false);assert.equal(handled,1);});
  it("reclaims a job after its prior worker lease expires",async()=>{let now=10_000;const queue=new InMemoryDurableJobQueue(()=>now);await queue.enqueue({queueName:"execution",jobType:"submit",payload:{proposalId:"proposal-1"},idempotencyKey:"lease-recovery-key"});const abandoned=await queue.claim("execution","crashed-worker",500);assert.ok(abandoned);now=10_501;const recovered=await queue.claim("execution","replacement-worker",500);assert.equal(recovered?.id,abandoned.id);assert.equal(recovered?.leasedBy,"replacement-worker");await queue.complete(recovered!.id,"replacement-worker");});
  it("reclaims an expired PostgreSQL lease after a worker crash",{skip:process.env.TEST_DATABASE_URL===undefined},async()=>{const databaseUrl=process.env.TEST_DATABASE_URL!;const queue=PostgresDurableJobQueue.connect(databaseUrl);const admin=new Pool({connectionString:databaseUrl});const suffix=randomUUID();try{const id=await queue.enqueue({queueName:`lease-recovery-${suffix}`,jobType:"submit",payload:{proposalId:suffix},idempotencyKey:`lease-recovery-${suffix}`});const abandoned=await queue.claim(`lease-recovery-${suffix}`,"crashed-worker",60_000);assert.equal(abandoned?.id,id);await admin.query(`UPDATE queue_jobs SET leased_until=clock_timestamp()-interval '1 second' WHERE id=$1`,[id]);const recovered=await queue.claim(`lease-recovery-${suffix}`,"replacement-worker",60_000);assert.equal(recovered?.id,id);assert.equal(recovered?.leasedBy,"replacement-worker");await queue.complete(id,"replacement-worker");}finally{await queue.close();await admin.end();}});
});
