import { randomUUID } from "node:crypto";
import { DomainError } from "@whox/contracts";
import type { Pool } from "pg";

export type NotificationPriority="summary"|"normal"|"time_sensitive"|"critical";
export interface QuietHours {readonly startMinute:number;readonly endMinute:number;readonly utcOffsetMinutes:number;}
export interface NotificationJobPayload extends Readonly<Record<string,unknown>> {
  readonly notificationType:string;readonly priority:NotificationPriority;readonly title:string;readonly privateBody:string;readonly publicBody?:string;
  readonly deepLink?:string;readonly occurredAt:string;readonly notificationIdempotencyKey:string;
}
export interface NotificationDeliveryPolicy {readonly detailedPreviewsEnabled:boolean;readonly criticalNotificationsEnabled:boolean;readonly quietHours?:QuietHours;}
export interface PushMessage {readonly userId:string;readonly title:string;readonly body:string;readonly priority:NotificationPriority;readonly deepLink?:string;readonly collapseId:string;}
export interface PushProvider {deliver(message:PushMessage):Promise<void>;}
export interface QueuedNotification {readonly id:string;readonly deliveredAt?:string;}
export interface NotificationRepository {deliveryPolicy(userId:string):Promise<NotificationDeliveryPolicy>;recordQueued(userId:string,payload:NotificationJobPayload,scheduledAt:string):Promise<QueuedNotification>;markDelivered(userId:string,id:string,deliveredAt:string):Promise<void>;markFailed(userId:string,id:string,failedAt:string,errorCode:string):Promise<void>;}

const SAFE_DELIVERY_POLICY:NotificationDeliveryPolicy=Object.freeze({detailedPreviewsEnabled:false,criticalNotificationsEnabled:false});

export class MemoryNotificationRepository implements NotificationRepository {
  readonly #records=new Map<string,{readonly id:string;readonly fingerprint:string;deliveredAt?:string;status:"queued"|"delivered"|"failed"}>();
  public constructor(private readonly policy:NotificationDeliveryPolicy=SAFE_DELIVERY_POLICY){}
  public async deliveryPolicy():Promise<NotificationDeliveryPolicy>{return this.policy;}
  public async recordQueued(userId:string,payload:NotificationJobPayload):Promise<QueuedNotification>{const fingerprint=JSON.stringify({userId,payload});const prior=this.#records.get(payload.notificationIdempotencyKey);if(prior!==undefined){if(prior.fingerprint!==fingerprint)throw new DomainError("NOTIFICATION_IDEMPOTENCY_REUSED","Notification key was reused with a different payload",409);return Object.freeze({id:prior.id,...(prior.deliveredAt===undefined?{}:{deliveredAt:prior.deliveredAt})});}const id=randomUUID();this.#records.set(payload.notificationIdempotencyKey,{id,fingerprint,status:"queued"});return Object.freeze({id});}
  public async markDelivered(_userId:string,id:string,deliveredAt:string):Promise<void>{const record=[...this.#records.values()].find((item)=>item.id===id);if(record===undefined)throw new DomainError("NOTIFICATION_NOT_FOUND","Notification was not found",404);record.status="delivered";record.deliveredAt=deliveredAt;}
  public async markFailed(_userId:string,id:string):Promise<void>{const record=[...this.#records.values()].find((item)=>item.id===id);if(record===undefined)throw new DomainError("NOTIFICATION_NOT_FOUND","Notification was not found",404);if(record.status!=="delivered")record.status="failed";}
}

export class PostgresNotificationRepository implements NotificationRepository {
  public constructor(private readonly pool:Pool){}
  public async deliveryPolicy(userId:string):Promise<NotificationDeliveryPolicy>{return this.withTenant(userId,async(client)=>{const result=await client.query<{profile:unknown}>(`SELECT profile FROM user_profiles WHERE user_id=$1`,[userId]);const profile=record(result.rows[0]?.profile);const preferences=record(profile.notificationPreferences);const detailedPreviewsEnabled=preferences.detailedPreviewsEnabled===true;const criticalNotificationsEnabled=preferences.criticalNotificationsEnabled===true;const quietHours=parseStoredQuietHours(preferences.quietHours);return Object.freeze({detailedPreviewsEnabled,criticalNotificationsEnabled,...(quietHours===undefined?{}:{quietHours})});});}
  public async recordQueued(userId:string,payload:NotificationJobPayload,scheduledAt:string):Promise<QueuedNotification>{return this.withTenant(userId,async(client)=>{const result=await client.query<{id:string;status:string;deliveredAt:string|null}>(`INSERT INTO notifications(user_id,notification_type,priority,title,private_body,public_body,deep_link,status,idempotency_key,scheduled_at)
    VALUES($1,$2,$3,$4,$5,$6,$7,'queued',$8,$9::timestamptz) ON CONFLICT(idempotency_key) DO UPDATE SET idempotency_key=EXCLUDED.idempotency_key
    WHERE notifications.user_id=EXCLUDED.user_id AND notifications.notification_type=EXCLUDED.notification_type AND notifications.priority=EXCLUDED.priority AND notifications.title=EXCLUDED.title AND notifications.private_body=EXCLUDED.private_body AND notifications.public_body IS NOT DISTINCT FROM EXCLUDED.public_body AND notifications.deep_link IS NOT DISTINCT FROM EXCLUDED.deep_link
    RETURNING id,status,delivered_at::text AS "deliveredAt"`,[userId,payload.notificationType,payload.priority,payload.title,payload.privateBody,payload.publicBody??null,payload.deepLink??null,payload.notificationIdempotencyKey,scheduledAt]);const row=result.rows[0];if(row===undefined)throw new DomainError("NOTIFICATION_IDEMPOTENCY_REUSED","Notification key was reused with a different payload",409);return Object.freeze({id:row.id,...(["delivered","read"].includes(row.status)&&row.deliveredAt!==null?{deliveredAt:row.deliveredAt}:{})});});}
  public async markDelivered(userId:string,id:string,deliveredAt:string):Promise<void>{await this.withTenant(userId,async(client)=>{const result=await client.query(`UPDATE notifications SET status='delivered',delivered_at=$2::timestamptz,attempts=attempts+1 WHERE id=$1 AND status IN ('queued','failed')`,[id,deliveredAt]);if(result.rowCount!==1)throw new DomainError("NOTIFICATION_STATE_INVALID","Notification was not deliverable",409);});}
  public async markFailed(userId:string,id:string,failedAt:string,errorCode:string):Promise<void>{await this.withTenant(userId,async(client)=>{const result=await client.query(`UPDATE notifications SET status='failed',attempts=attempts+1 WHERE id=$1 AND user_id=$2 AND status IN ('queued','failed')`,[id,userId]);if(result.rowCount!==1)throw new DomainError("NOTIFICATION_STATE_INVALID","Notification was not in a retryable state",409);await client.query(`INSERT INTO audit_events(user_id,actor_id,actor_role,action,resource_type,resource_id,after_state,correlation_id,occurred_at)
      VALUES($1,'notification-worker','worker','notification.delivery_failed','notification',$2,$3::jsonb,$4,$5::timestamptz)`,[userId,id,JSON.stringify({errorCode}),`notification-failure:${id}:${failedAt}`,failedAt]);});}
  private async withTenant<T>(userId:string,work:(client:import("pg").PoolClient)=>Promise<T>):Promise<T>{const client=await this.pool.connect();try{await client.query("BEGIN");await client.query("SET LOCAL ROLE whox_notification_worker");await client.query("SET LOCAL statement_timeout='10s'");await client.query(`SELECT set_config('app.user_id',$1,true)`,[userId]);const value=await work(client);await client.query("COMMIT");return value;}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}
}

export class InMemoryPushProvider implements PushProvider {public readonly deliveries:PushMessage[]=[];public async deliver(message:PushMessage):Promise<void>{this.deliveries.push(Object.freeze(message));}}
export class UnconfiguredPushProvider implements PushProvider {public async deliver():Promise<void>{throw new DomainError("PUSH_PROVIDER_UNCONFIGURED","APNs provider credentials and transport are not configured",503);}}

export class NotificationProcessor {
  public constructor(private readonly repository:NotificationRepository,private readonly provider:PushProvider){}
  public async process(userId:string,value:unknown,now:string):Promise<{readonly id:string;readonly deliveredAt:string}>{const payload=validateNotificationPayload(value);const queued=await this.repository.recordQueued(userId,payload,now);if(queued.deliveredAt!==undefined)return Object.freeze({id:queued.id,deliveredAt:queued.deliveredAt});const policy=await this.repository.deliveryPolicy(userId);const deferred=quietHoursEnd(payload,policy,now);if(deferred!==undefined)throw new NotificationQuietHoursError(deferred);const body=policy.detailedPreviewsEnabled?payload.privateBody:(payload.publicBody??"Open Yield to view this notification.");const message:PushMessage={userId,title:payload.title,body,priority:payload.priority,collapseId:payload.notificationIdempotencyKey,...(payload.deepLink===undefined?{}:{deepLink:payload.deepLink})};try{await this.provider.deliver(Object.freeze(message));}catch(error){const errorCode=error instanceof DomainError?error.code:"PUSH_DELIVERY_FAILED";await this.repository.markFailed(userId,queued.id,now,errorCode);throw error;}await this.repository.markDelivered(userId,queued.id,now);return Object.freeze({id:queued.id,deliveredAt:now});}
}

export class NotificationQuietHoursError extends Error {public constructor(readonly availableAt:string){super("Notification deferred by quiet hours");this.name="NotificationQuietHoursError";}}

export function validateNotificationPayload(value:unknown):NotificationJobPayload{if(typeof value!=="object"||value===null||Array.isArray(value))throw new DomainError("NOTIFICATION_PAYLOAD_INVALID","Notification payload must be an object",422);const item=value as Record<string,unknown>;const priorities:readonly string[]=["summary","normal","time_sensitive","critical"];if(typeof item.notificationType!=="string"||item.notificationType.length<1||typeof item.title!=="string"||item.title.length<1||item.title.length>120||typeof item.privateBody!=="string"||item.privateBody.length<1||!priorities.includes(String(item.priority))||typeof item.occurredAt!=="string"||!Number.isFinite(Date.parse(item.occurredAt))||typeof item.notificationIdempotencyKey!=="string"||item.notificationIdempotencyKey.length<8)throw new DomainError("NOTIFICATION_PAYLOAD_INVALID","Notification payload fields are invalid",422);if(item.publicBody!==undefined&&typeof item.publicBody!=="string")throw new DomainError("NOTIFICATION_PAYLOAD_INVALID","Public notification body is invalid",422);if(item.deepLink!==undefined&&(typeof item.deepLink!=="string"||!/^yield:\/\/(?:dashboard|proposals|active-agent|risk(?:\/pause)?|(?:activity|agent|position)\/[A-Za-z0-9._:-]{1,128})$/.test(item.deepLink)))throw new DomainError("NOTIFICATION_DEEP_LINK_INVALID","Notification deep link is not in the iOS route allowlist",422);
  return Object.freeze({notificationType:item.notificationType,priority:item.priority as NotificationPriority,title:item.title,privateBody:item.privateBody,...(item.publicBody===undefined?{}:{publicBody:item.publicBody as string}),...(item.deepLink===undefined?{}:{deepLink:item.deepLink as string}),occurredAt:item.occurredAt,notificationIdempotencyKey:item.notificationIdempotencyKey});}

export function quietHoursEnd(payload:NotificationJobPayload,policy:NotificationDeliveryPolicy,now:string):string|undefined{const quiet=policy.quietHours;if(quiet===undefined)return undefined;const criticalCategory=/^(risk|security)(_|$)/.test(payload.notificationType);if(criticalCategory&&policy.criticalNotificationsEnabled&&(payload.priority==="time_sensitive"||payload.priority==="critical"))return undefined;const instant=Date.parse(now);if(!Number.isFinite(instant))throw new TypeError("now must be an ISO timestamp");const local=new Date(instant+quiet.utcOffsetMinutes*60_000);const minute=local.getUTCHours()*60+local.getUTCMinutes();const wraps=quiet.startMinute>quiet.endMinute;const within=quiet.startMinute===quiet.endMinute?false:wraps?(minute>=quiet.startMinute||minute<quiet.endMinute):(minute>=quiet.startMinute&&minute<quiet.endMinute);if(!within)return undefined;const localDay=Date.UTC(local.getUTCFullYear(),local.getUTCMonth(),local.getUTCDate());const endDayOffset=wraps&&minute>=quiet.startMinute?24*60:0;return new Date(localDay+(endDayOffset+quiet.endMinute-quiet.utcOffsetMinutes)*60_000).toISOString();}

function record(value:unknown):Readonly<Record<string,unknown>>{return typeof value==="object"&&value!==null&&!Array.isArray(value)?value as Readonly<Record<string,unknown>>:{};}
function parseStoredQuietHours(value:unknown):QuietHours|undefined{const item=record(value);if(!Number.isInteger(item.startMinute)||!Number.isInteger(item.endMinute)||!Number.isInteger(item.utcOffsetMinutes)||Number(item.startMinute)<0||Number(item.startMinute)>1439||Number(item.endMinute)<0||Number(item.endMinute)>1439||Number(item.utcOffsetMinutes)<-840||Number(item.utcOffsetMinutes)>840)return undefined;return Object.freeze({startMinute:Number(item.startMinute),endMinute:Number(item.endMinute),utcOffsetMinutes:Number(item.utcOffsetMinutes)});}
