import { DomainError } from "@whox/contracts";
import { DeferJobError, InMemoryCoordinationAdapter, InMemoryDurableJobQueue, PollingWorker, PostgresDurableJobQueue, RedisCoordinationAdapter, startWorkerHealthServer, type CoordinationAdapter, type DurableJobQueue } from "@whox/agent-orchestrator";
import { parseRuntimeMode } from "@whox/shared-config";
import { Pool } from "pg";
import { APNsPushProvider, PostgresAPNsDeviceTargetSource, type APNsEnvironment } from "./apns.js";
import { InMemoryPushProvider, MemoryNotificationRepository, NotificationProcessor, NotificationQuietHoursError, PostgresNotificationRepository, type PushProvider } from "./index.js";

function port():number{const value=Number(process.env.HEALTH_PORT??9103);if(!Number.isInteger(value)||value<1||value>65_535)throw new DomainError("WORKER_PORT_INVALID","HEALTH_PORT is invalid",500);return value;}
function required(name:string):string{const value=process.env[name]?.trim();if(value===undefined||value.length===0||/(replace|placeholder|example|not[_ -]?for[_ -]?production)/i.test(value))throw new DomainError("PUSH_CONFIGURATION_REQUIRED",`${name} must be configured for non-Demo notification delivery`,500);return value;}
function apnsEnvironments():ReadonlySet<APNsEnvironment>{const values=required("APNS_ENVIRONMENTS").split(",").map((item)=>item.trim()).filter(Boolean);if(values.length===0||values.some((item)=>item!=="sandbox"&&item!=="production"))throw new DomainError("PUSH_CONFIGURATION_INVALID","APNS_ENVIRONMENTS must contain sandbox and/or production",500);return new Set(values as APNsEnvironment[]);}
function providerFor(mode:"demo"|"paper"|"live",pool:Pool|undefined):PushProvider{if(mode==="demo")return new InMemoryPushProvider();if(pool===undefined)throw new DomainError("DATABASE_URL_REQUIRED","APNs delivery requires PostgreSQL device targets",500);const tokenSecret=Buffer.from(required("DEVICE_TOKEN_ENCRYPTION_KEY"),"utf8");if(tokenSecret.length<32)throw new DomainError("PUSH_CONFIGURATION_INVALID","DEVICE_TOKEN_ENCRYPTION_KEY must contain at least 32 bytes",500);const privateKey=required("APNS_PRIVATE_KEY").replaceAll("\\n","\n");return new APNsPushProvider({teamId:required("APNS_TEAM_ID"),keyId:required("APNS_KEY_ID"),privateKey,topic:required("APNS_TOPIC"),allowedEnvironments:apnsEnvironments()},new PostgresAPNsDeviceTargetSource(pool,tokenSecret));}
async function main():Promise<void>{const mode=parseRuntimeMode(process.env.APP_ENV);const databaseUrl=process.env.DATABASE_URL?.trim();const redisUrl=process.env.REDIS_URL?.trim();if(mode!=="demo"&&!databaseUrl)throw new DomainError("DATABASE_URL_REQUIRED","Paper and Live notification workers require PostgreSQL",500);if(mode!=="demo"&&!redisUrl)throw new DomainError("REDIS_URL_REQUIRED","Paper and Live notification workers require Redis",500);const queue:DurableJobQueue=databaseUrl?PostgresDurableJobQueue.connect(databaseUrl):new InMemoryDurableJobQueue();const coordination:CoordinationAdapter=redisUrl?await RedisCoordinationAdapter.connect(redisUrl,"whox-notification"):new InMemoryCoordinationAdapter();const pool=databaseUrl?new Pool({connectionString:databaseUrl,application_name:"whox-notification-worker",max:4}):undefined;const repository=pool?new PostgresNotificationRepository(pool):new MemoryNotificationRepository();const provider=providerFor(mode,pool);const processor=new NotificationProcessor(repository,provider);const worker=new PollingWorker("notification-worker",queue,"notifications",async(job)=>{const lock=await coordination.acquireLock(`job:${job.id}`,30_000);if(lock===undefined)throw new DomainError("NOTIFICATION_JOB_LOCKED","Notification job is already locked",409);try{if(job.userId===undefined)throw new DomainError("NOTIFICATION_USER_REQUIRED","Notification job must be tenant-bound",422);try{await processor.process(job.userId,job.payload,new Date().toISOString());}catch(error){if(error instanceof NotificationQuietHoursError)throw new DeferJobError(error.availableAt);throw error;}}finally{await coordination.releaseLock(lock);}});const health=startWorkerHealthServer(worker,port());const controller=new AbortController();const stop=():void=>controller.abort();process.once("SIGTERM",stop);process.once("SIGINT",stop);process.stdout.write(JSON.stringify({event:"worker_started",service:"notification-worker",mode,healthPort:port()})+"\n");await worker.run(controller.signal);await new Promise<void>((resolve)=>health.close(()=>resolve()));await worker.stop();await coordination.close();if(provider instanceof APNsPushProvider)await provider.close();if(pool)await pool.end();}
void main().catch((error:unknown)=>{process.stderr.write(JSON.stringify({event:"worker_start_failed",service:"notification-worker",code:error instanceof DomainError?error.code:"WORKER_START_FAILED"})+"\n");process.exitCode=1;});
