import { createHash, createPublicKey, verify as verifySignature, type JsonWebKey } from "node:crypto";
import { DomainError } from "@whox/contracts";
import type { AppleIdentity, AppleIdentityVerificationContext, AppleIdentityVerifier } from "./security.js";

interface AppleJwk extends JsonWebKey {readonly kid?:string;readonly alg?:string;readonly use?:string;}
interface AppleJwks {readonly keys?:readonly AppleJwk[];}

export interface AppleIdentityTokenVerifierOptions {
  readonly clientId:string;
  readonly issuer?:string;
  readonly jwksUrl?:URL;
  readonly fetcher?:typeof fetch;
  readonly maximumTokenAgeSeconds?:number;
  readonly jwksCacheMs?:number;
}

export class UnavailableAppleIdentityVerifier implements AppleIdentityVerifier {
  public async verify():Promise<AppleIdentity>{throw new DomainError("APPLE_IDENTITY_VERIFIER_UNAVAILABLE","Apple identity-token verification is not configured",503);}
}

export class AppleIdentityTokenVerifier implements AppleIdentityVerifier {
  readonly #issuer:string;readonly #jwksUrl:URL;readonly #fetcher:typeof fetch;readonly #maximumTokenAgeSeconds:number;readonly #jwksCacheMs:number;
  #cached:{readonly expiresAt:number;readonly keys:readonly AppleJwk[]}|undefined;
  readonly #consumedAssertions=new Map<string,number>();
  public constructor(private readonly options:AppleIdentityTokenVerifierOptions){if(options.clientId.trim()==="")throw new TypeError("Apple client ID is required");this.#issuer=options.issuer??"https://appleid.apple.com";this.#jwksUrl=options.jwksUrl??new URL("https://appleid.apple.com/auth/keys");if(this.#issuer!=="https://appleid.apple.com"||this.#jwksUrl.protocol!=="https:")throw new TypeError("Apple identity verification must use the official HTTPS issuer and JWKS endpoint");this.#fetcher=options.fetcher??fetch;this.#maximumTokenAgeSeconds=options.maximumTokenAgeSeconds??10*60;this.#jwksCacheMs=options.jwksCacheMs??60*60_000;}
  async #keys(now:number):Promise<readonly AppleJwk[]>{if(this.#cached!==undefined&&this.#cached.expiresAt>now)return this.#cached.keys;let response:Response;try{response=await this.#fetcher(this.#jwksUrl,{headers:{accept:"application/json"},redirect:"error",signal:AbortSignal.timeout(5_000)});}catch{throw new DomainError("APPLE_JWKS_UNAVAILABLE","Apple signing keys could not be retrieved",503);}if(!response.ok)throw new DomainError("APPLE_JWKS_UNAVAILABLE","Apple signing keys could not be retrieved",503);let value:unknown;try{value=await response.json();}catch{throw new DomainError("APPLE_JWKS_INVALID","Apple signing-key response is invalid",503);}if(typeof value!=="object"||value===null||!Array.isArray((value as AppleJwks).keys))throw new DomainError("APPLE_JWKS_INVALID","Apple signing-key response is invalid",503);const keys=(value as AppleJwks).keys!.filter((key)=>key.kty==="RSA"&&typeof key.kid==="string"&&(key.alg===undefined||key.alg==="RS256")&&(key.use===undefined||key.use==="sig"));if(keys.length===0)throw new DomainError("APPLE_JWKS_INVALID","Apple signing-key response contains no usable RS256 key",503);this.#cached={keys:Object.freeze(keys),expiresAt:now+this.#jwksCacheMs};return this.#cached.keys;}
  public async verify(identityToken:string,context:AppleIdentityVerificationContext={}):Promise<AppleIdentity>{const parts=identityToken.split(".");if(parts.length!==3)throw new DomainError("APPLE_IDENTITY_INVALID","Apple identity token is invalid",401);let header:Readonly<Record<string,unknown>>;let claims:Readonly<Record<string,unknown>>;try{header=JSON.parse(Buffer.from(parts[0]!,"base64url").toString("utf8")) as Readonly<Record<string,unknown>>;claims=JSON.parse(Buffer.from(parts[1]!,"base64url").toString("utf8")) as Readonly<Record<string,unknown>>;}catch{throw new DomainError("APPLE_IDENTITY_INVALID","Apple identity token is invalid",401);}if(header.alg!=="RS256"||typeof header.kid!=="string")throw new DomainError("APPLE_IDENTITY_INVALID","Apple identity token algorithm or key identifier is invalid",401);const now=context.now??new Date();const key=(await this.#keys(now.getTime())).find((candidate)=>candidate.kid===header.kid);if(key===undefined){this.#cached=undefined;const refreshed=(await this.#keys(now.getTime())).find((candidate)=>candidate.kid===header.kid);if(refreshed===undefined)throw new DomainError("APPLE_IDENTITY_INVALID","Apple identity token signing key is unknown",401);return await this.#verifyWithKey(identityToken,parts,claims,refreshed,context,now);}return await this.#verifyWithKey(identityToken,parts,claims,key,context,now);}
  async #verifyWithKey(token:string,parts:readonly string[],claims:Readonly<Record<string,unknown>>,jwk:AppleJwk,context:AppleIdentityVerificationContext,now:Date):Promise<AppleIdentity>{let signature:Buffer;try{signature=Buffer.from(parts[2]!,"base64url");}catch{throw new DomainError("APPLE_IDENTITY_INVALID","Apple identity token signature is invalid",401);}let publicKey;try{publicKey=createPublicKey({key:jwk,format:"jwk"});}catch{throw new DomainError("APPLE_JWKS_INVALID","Apple signing key is invalid",503);}if(!verifySignature("RSA-SHA256",Buffer.from(`${parts[0]}.${parts[1]}`),publicKey,signature))throw new DomainError("APPLE_IDENTITY_INVALID","Apple identity token signature is invalid",401);const audience=claims.aud;const audienceMatches=audience===this.options.clientId||(Array.isArray(audience)&&audience.includes(this.options.clientId));const nowSeconds=Math.floor(now.getTime()/1000);if(claims.iss!==this.#issuer||!audienceMatches||typeof claims.sub!=="string"||claims.sub.length<3||typeof claims.exp!=="number"||typeof claims.iat!=="number"||!Number.isInteger(claims.exp)||!Number.isInteger(claims.iat)||claims.exp<=nowSeconds||claims.iat>nowSeconds+30||nowSeconds-claims.iat>this.#maximumTokenAgeSeconds)throw new DomainError("APPLE_IDENTITY_INVALID","Apple identity token claims are invalid or expired",401);if(context.nonce===undefined||context.nonce.length<16||context.nonce.length>256)throw new DomainError("APPLE_NONCE_REQUIRED","A valid raw Sign in with Apple nonce is required",401);const expectedNonce=createHash("sha256").update(context.nonce,"utf8").digest("hex");if(claims.nonce!==expectedNonce)throw new DomainError("APPLE_IDENTITY_INVALID","Apple identity token nonce does not match the raw nonce digest",401);for(const[digest,expiresAt]of this.#consumedAssertions)if(expiresAt<=nowSeconds)this.#consumedAssertions.delete(digest);const assertionDigest=createHash("sha256").update(token,"utf8").digest("hex");if(this.#consumedAssertions.has(assertionDigest))throw new DomainError("APPLE_IDENTITY_REPLAYED","Apple identity token was already consumed",401);this.#consumedAssertions.set(assertionDigest,claims.exp);const email=typeof claims.email==="string"?claims.email:undefined;const emailVerified=claims.email_verified===true||claims.email_verified==="true";return Object.freeze({appleSubject:claims.sub,emailVerified,assertionDigest,assertionExpiresAt:new Date(claims.exp*1000).toISOString(),...(email===undefined?{}:{email})});}
}
