import { createHash, createHmac, randomBytes, randomUUID, timingSafeEqual } from "node:crypto";
import { DomainError, type ApprovedBrokerConnectorIdentity, type BrokerAuthorizationCompletion, type BrokerAuthorizationExchangeOperation, type BrokerAuthorizationExchangePersistence, type BrokerAuthorizationExchangeWork, type BrokerAuthorizationSagaOperation, type BrokerAuthorizationSagaPersistence, type BrokerAuthorizationSagaWork, type BrokerConnectionSummary } from "@whox/contracts";

const alphabet="23456789ABCDEFGHJKLMNPQRSTUVWXYZ";
const normalizeCode=(code:string):string=>code.toUpperCase().replace(/[^A-Z0-9]/g,"");
function makeCode():string{const bytes=randomBytes(8);let raw="";for(const byte of bytes)raw+=alphabet[byte%alphabet.length];return `${raw.slice(0,4)}-${raw.slice(4)}`;}
export interface PairingRepresentation {readonly pairingId:string;readonly code:string;readonly setupUrl:string;readonly expiresAt:string;readonly status:"pending"|"authorizing"|"connected"|"expired"|"canceled"|"error";readonly connection?:BrokerConnectionSummary;}
export interface MobileAuthorizationArtifacts {readonly state:string;readonly nonce:string;readonly codeChallenge:string;readonly codeChallengeMethod:"S256";readonly expiresAt:string;readonly resumed:boolean;}
export interface MobileCallbackSecrets {readonly ownerUserId:string;readonly creatorSessionId:string;readonly pairingId:string;readonly codeVerifier:string;readonly nonce:string;readonly redirectUri:string;readonly mobileReturnUri:string;}
export type BrokerAuthorizationRevocationTarget =
  | {readonly kind:"saga";readonly authorizationSagaId:string}
  | {readonly kind:"exchange";readonly exchangeTransactionId:string}
  | {readonly kind:"demo"}
  | {readonly kind:"none"}
  | {readonly kind:"unmanaged"};
export interface PairingServiceContract extends Partial<BrokerAuthorizationSagaPersistence>, Partial<BrokerAuthorizationExchangePersistence> {
  readonly persistenceKind:"ephemeral"|"persistent";
  readonly approvedConnectorIdentity:ApprovedBrokerConnectorIdentity|undefined;
  create(ownerUserId:string,creatorSessionId:string,now:string):PairingRepresentation|Promise<PairingRepresentation>;
  get(ownerUserId:string,sessionId:string,pairingId:string,now:string):PairingRepresentation|Promise<PairingRepresentation>;
  claim(ownerUserId:string,claimantSessionId:string,code:string,attemptKey:string,now:string):PairingRepresentation|Promise<PairingRepresentation>;
  beginAuthorization(ownerUserId:string,sessionId:string,pairingId:string,now:string):string|Promise<string>;
  completeForSession(ownerUserId:string,claimantSessionId:string,pairingId:string,authorizationState:string,completion:BrokerConnectionSummary|BrokerAuthorizationCompletion,now:string):void|Promise<void>;
  cancel(ownerUserId:string,sessionId:string,pairingId:string,now:string):void|Promise<void>;
  beginMobileAuthorization?(ownerUserId:string,creatorSessionId:string,pairingId:string,redirectUri:string,mobileReturnUri:string,now:string):Promise<MobileAuthorizationArtifacts>;
  resetMobileAuthorization?(ownerUserId:string,creatorSessionId:string,pairingId:string,state:string,now:string):Promise<void>;
  abortMobileAuthorization?(ownerUserId:string,creatorSessionId:string,pairingId:string,now:string):Promise<void>;
  mobileCallbackSecrets?(state:string,now:string):Promise<MobileCallbackSecrets>;
  beginMobileExchangeForSession?(ownerUserId:string,creatorSessionId:string,pairingId:string,state:string,exchangeTransactionId:string,cleanupAfter:string,now:string):Promise<void>;
  completeMobileForSession?(ownerUserId:string,creatorSessionId:string,pairingId:string,state:string,exchangeTransactionId:string,provisionalCredentialExpiresAt:string,completion:BrokerConnectionSummary|BrokerAuthorizationCompletion,now:string):Promise<{readonly authorizationSagaId:string}>;
  concludeMobileWithoutConnection?(ownerUserId:string,creatorSessionId:string,pairingId:string,state:string,outcome:"canceled"|"error",now:string):Promise<void>;
  authorizationRevocationTarget?(ownerUserId:string,now:string):Promise<BrokerAuthorizationRevocationTarget>;
  disconnectDemoAuthorization?(ownerUserId:string,now:string):Promise<void>;
  healthy():boolean|Promise<boolean>;
}
interface PairingRecord {readonly pairingId:string;readonly ownerUserId:string;readonly creatorSessionId:string;readonly codeHash:string;codeDisplay:string;readonly setupUrl:string;readonly createdAt:string;readonly expiresAt:string;status:PairingRepresentation["status"];claimedAt?:string;claimantSessionId?:string;authorizationStateHash?:string;authorizationStateExpiresAt?:string;oauthFlow?:"desktop"|"mobile";mobileState?:string;mobileCodeVerifier?:string;mobileNonce?:string;mobileRedirectUri?:string;mobileReturnUri?:string;mobileCallbackClaimedAt?:string;mobileCredentialHandle?:string;mobileCredentialConfirmedAt?:string;mobileAuthorizationSagaId?:string;mobileExchangeTransactionId?:string;mobileExchangeCleanupAfter?:string;mobileExchangeOperation?:BrokerAuthorizationExchangeOperation;mobileConfirmationDeadlineAt?:string;mobileSagaOperation?:BrokerAuthorizationSagaOperation;mobileSagaIdentity?:ApprovedBrokerConnectorIdentity;mobileCompletion?:BrokerAuthorizationCompletion;consumedAt?:string;connection?:BrokerConnectionSummary;}

export class PairingService {
  public readonly persistenceKind:"ephemeral"|"persistent"="ephemeral";
  readonly #records=new Map<string,PairingRecord>();readonly #attempts=new Map<string,{count:number;resetAt:number}>();
  public constructor(private readonly connectionWebBaseUrl:URL,private readonly hashPepper:Buffer,private readonly ttlMs=10*60_000,public readonly approvedConnectorIdentity:ApprovedBrokerConnectorIdentity|undefined=undefined){if(hashPepper.length<32)throw new TypeError("PAIRING_HASH_PEPPER must contain at least 32 bytes");}
  #digestCode(code:string):string{return createHmac("sha256",this.hashPepper).update(normalizeCode(code)).digest("hex");}
  #digestAuthorizationState(state:string):string{return createHmac("sha256",this.hashPepper).update(state,"utf8").digest("hex");}
  #representation(record:PairingRecord,includeCode:boolean,now:string):PairingRepresentation{if(record.consumedAt===undefined&&record.status!=="connected"&&record.status!=="canceled"&&Date.parse(record.expiresAt)<=Date.parse(now))record.status="expired";return Object.freeze({pairingId:record.pairingId,code:includeCode?record.codeDisplay:"",setupUrl:record.setupUrl,expiresAt:record.expiresAt,status:record.status,...(record.connection===undefined?{}:{connection:record.connection})});}
  public create(ownerUserId:string,creatorSessionId:string,now:string):PairingRepresentation{const pairingId=randomUUID();const code=makeCode();const setup=new URL("/pair",this.connectionWebBaseUrl);setup.searchParams.set("pairing_code",code);const record:PairingRecord={pairingId,ownerUserId,creatorSessionId,codeHash:this.#digestCode(code),codeDisplay:code,setupUrl:setup.href,createdAt:now,expiresAt:new Date(Date.parse(now)+this.ttlMs).toISOString(),status:"pending"};this.#records.set(pairingId,record);return this.#representation(record,true,now);}
  public get(ownerUserId:string,sessionId:string,pairingId:string,now:string):PairingRepresentation{const record=this.#records.get(pairingId);if(record===undefined||record.ownerUserId!==ownerUserId||(record.creatorSessionId!==sessionId&&record.claimantSessionId!==sessionId))throw new DomainError("PAIRING_NOT_FOUND","Pairing was not found",404);return this.#representation(record,true,now);}
  public claim(ownerUserId:string,claimantSessionId:string,code:string,attemptKey:string,now:string):PairingRepresentation{const instant=Date.parse(now);const limit=this.#attempts.get(attemptKey);if(limit!==undefined&&limit.resetAt>instant&&limit.count>=5)throw new DomainError("PAIRING_ATTEMPTS_EXCEEDED","Too many pairing attempts",429);const hash=Buffer.from(this.#digestCode(code));let match:PairingRecord|undefined;for(const record of this.#records.values()){const expected=Buffer.from(record.codeHash);if(expected.length===hash.length&&timingSafeEqual(expected,hash))match=record;}
    if(match===undefined||match.ownerUserId!==ownerUserId){this.#attempts.set(attemptKey,{count:(limit?.resetAt??0)>instant?(limit?.count??0)+1:1,resetAt:instant+15*60_000});throw new DomainError("PAIRING_CODE_INVALID","Pairing code is invalid or expired",404);}const value=this.#representation(match,true,now);if(value.status!=="pending"||match.claimedAt!==undefined)throw new DomainError("PAIRING_CODE_USED","Pairing code cannot be reused",409);match.claimedAt=now;match.claimantSessionId=claimantSessionId;return value;}
  public beginAuthorization(ownerUserId:string,sessionId:string,pairingId:string,now:string):string{const record=this.#records.get(pairingId);if(record===undefined||record.ownerUserId!==ownerUserId||record.claimantSessionId!==sessionId)throw new DomainError("PAIRING_NOT_FOUND","Pairing was not found",404);const current=this.#representation(record,false,now);if(current.status!=="pending"||record.claimedAt===undefined)throw new DomainError("PAIRING_NOT_PENDING","Pairing is not available for authorization",409);const state=randomBytes(32).toString("base64url");record.authorizationStateHash=this.#digestAuthorizationState(state);record.authorizationStateExpiresAt=new Date(Math.min(Date.parse(record.expiresAt),Date.parse(now)+5*60_000)).toISOString();record.oauthFlow="desktop";record.status="authorizing";return state;}
  public completeForSession(ownerUserId:string,claimantSessionId:string,pairingId:string,authorizationState:string,completion:BrokerConnectionSummary|BrokerAuthorizationCompletion,now:string):void{const record=this.#records.get(pairingId);const supplied=Buffer.from(this.#digestAuthorizationState(authorizationState));const expected=Buffer.from(record?.authorizationStateHash??"");const stateMatches=expected.length===supplied.length&&timingSafeEqual(expected,supplied);if(record===undefined||record.ownerUserId!==ownerUserId||record.claimantSessionId!==claimantSessionId||record.status!=="authorizing"||Date.parse(record.expiresAt)<=Date.parse(now)||record.authorizationStateExpiresAt===undefined||Date.parse(record.authorizationStateExpiresAt)<=Date.parse(now)||!stateMatches)throw new DomainError("PAIRING_INVALID","Pairing callback is invalid or expired",400);record.status="connected";record.connection="connection" in completion?completion.connection:completion;record.consumedAt=now;record.codeDisplay="";delete record.authorizationStateHash;delete record.authorizationStateExpiresAt;}
  public cancel(ownerUserId:string,sessionId:string,pairingId:string,now:string):void{const record=this.#records.get(pairingId);if(record===undefined||record.ownerUserId!==ownerUserId||(record.creatorSessionId!==sessionId&&record.claimantSessionId!==sessionId))throw new DomainError("PAIRING_NOT_FOUND","Pairing was not found",404);if(record.status==="connected")throw new DomainError("PAIRING_ALREADY_CONNECTED","Connected pairing cannot be canceled",409);if(record.mobileCallbackClaimedAt!==undefined||record.mobileCredentialHandle!==undefined)throw new DomainError("PAIRING_AUTHORIZATION_COMMITTED","A consumed broker authorization cannot be canceled as an empty pairing",409);record.status="canceled";record.consumedAt=now;record.codeDisplay="";delete record.authorizationStateHash;delete record.authorizationStateExpiresAt;delete record.oauthFlow;delete record.mobileState;delete record.mobileCodeVerifier;delete record.mobileNonce;delete record.mobileRedirectUri;delete record.mobileReturnUri;}
  public async beginMobileAuthorization(ownerUserId:string,creatorSessionId:string,pairingId:string,redirectUri:string,mobileReturnUri:string,now:string):Promise<MobileAuthorizationArtifacts>{const record=this.#records.get(pairingId);if(record===undefined||record.ownerUserId!==ownerUserId||record.creatorSessionId!==creatorSessionId)throw new DomainError("PAIRING_NOT_FOUND","Pairing was not found",404);if([...this.#records.values()].some((candidate)=>candidate!==record&&candidate.ownerUserId===ownerUserId&&(candidate.connection!==undefined||(candidate.mobileSagaOperation!==undefined&&candidate.mobileSagaOperation!=="revoked")||(candidate.mobileExchangeOperation!==undefined&&!["completed","revoked"].includes(candidate.mobileExchangeOperation)))))throw new DomainError("BROKER_CONNECTION_REPLACEMENT_REQUIRES_REVOCATION","Existing broker authorization must be durably revoked before replacement",409);const current=this.#representation(record,false,now);if(current.status==="authorizing"&&record.oauthFlow==="mobile"&&record.mobileState!==undefined&&record.mobileCodeVerifier!==undefined&&record.mobileNonce!==undefined&&record.mobileCallbackClaimedAt===undefined&&record.authorizationStateExpiresAt!==undefined&&Date.parse(record.authorizationStateExpiresAt)>Date.parse(now)&&record.mobileRedirectUri===redirectUri&&record.mobileReturnUri===mobileReturnUri)return Object.freeze({state:record.mobileState,nonce:record.mobileNonce,codeChallenge:createHash("sha256").update(record.mobileCodeVerifier,"ascii").digest("base64url"),codeChallengeMethod:"S256",expiresAt:record.authorizationStateExpiresAt,resumed:true});if(current.status!=="pending"||record.claimedAt!==undefined)throw new DomainError("PAIRING_NOT_PENDING","Pairing is not available for mobile authorization",409);const state=randomBytes(32).toString("base64url");const nonce=randomBytes(32).toString("base64url");const verifier=randomBytes(48).toString("base64url");record.authorizationStateHash=this.#digestAuthorizationState(state);record.authorizationStateExpiresAt=new Date(Math.min(Date.parse(record.expiresAt),Date.parse(now)+5*60_000)).toISOString();record.oauthFlow="mobile";record.mobileState=state;record.mobileCodeVerifier=verifier;record.mobileNonce=nonce;record.mobileRedirectUri=redirectUri;record.mobileReturnUri=mobileReturnUri;record.status="authorizing";return Object.freeze({state,nonce,codeChallenge:createHash("sha256").update(verifier,"ascii").digest("base64url"),codeChallengeMethod:"S256",expiresAt:record.authorizationStateExpiresAt,resumed:false});}
  public async resetMobileAuthorization(ownerUserId:string,creatorSessionId:string,pairingId:string,state:string,_now:string):Promise<void>{const record=this.#records.get(pairingId);const supplied=Buffer.from(this.#digestAuthorizationState(state));const expected=Buffer.from(record?.authorizationStateHash??"");if(record===undefined||record.ownerUserId!==ownerUserId||record.creatorSessionId!==creatorSessionId||record.status!=="authorizing"||record.oauthFlow!=="mobile"||record.mobileCallbackClaimedAt!==undefined||expected.length!==supplied.length||!timingSafeEqual(expected,supplied))throw new DomainError("PAIRING_INVALID","Pairing authorization could not be reset",400);record.status="pending";delete record.authorizationStateHash;delete record.authorizationStateExpiresAt;delete record.oauthFlow;delete record.mobileState;delete record.mobileCodeVerifier;delete record.mobileNonce;delete record.mobileRedirectUri;delete record.mobileReturnUri;}
  public async abortMobileAuthorization(ownerUserId:string,creatorSessionId:string,pairingId:string,_now:string):Promise<void>{const record=this.#records.get(pairingId);if(record===undefined||record.ownerUserId!==ownerUserId||record.creatorSessionId!==creatorSessionId)throw new DomainError("PAIRING_NOT_FOUND","Pairing was not found",404);if(record.status==="pending")return;if(record.status!=="authorizing"||record.oauthFlow!=="mobile"||record.mobileCallbackClaimedAt!==undefined||record.mobileCodeVerifier===undefined)throw new DomainError("MOBILE_OAUTH_ABORT_UNAVAILABLE","Mobile authorization can no longer be aborted",409);record.status="pending";delete record.authorizationStateHash;delete record.authorizationStateExpiresAt;delete record.oauthFlow;delete record.mobileState;delete record.mobileCodeVerifier;delete record.mobileNonce;delete record.mobileRedirectUri;delete record.mobileReturnUri;}
  public async mobileCallbackSecrets(state:string,now:string):Promise<MobileCallbackSecrets>{const supplied=Buffer.from(this.#digestAuthorizationState(state));let match:PairingRecord|undefined;for(const record of this.#records.values()){const expected=Buffer.from(record.authorizationStateHash??"");if(expected.length===supplied.length&&timingSafeEqual(expected,supplied))match=record;}if(match===undefined||match.status!=="authorizing"||match.oauthFlow!=="mobile"||match.authorizationStateExpiresAt===undefined||Date.parse(match.authorizationStateExpiresAt)<=Date.parse(now)||Date.parse(match.expiresAt)<=Date.parse(now)||match.mobileCallbackClaimedAt!==undefined||match.mobileCodeVerifier===undefined||match.mobileNonce===undefined||match.mobileRedirectUri===undefined||match.mobileReturnUri===undefined)throw new DomainError("MOBILE_OAUTH_CALLBACK_INVALID","Mobile authorization callback is invalid or expired",400);match.mobileCallbackClaimedAt=now;const codeVerifier=match.mobileCodeVerifier;delete match.mobileState;delete match.mobileCodeVerifier;return Object.freeze({ownerUserId:match.ownerUserId,creatorSessionId:match.creatorSessionId,pairingId:match.pairingId,codeVerifier,nonce:match.mobileNonce,redirectUri:match.mobileRedirectUri,mobileReturnUri:match.mobileReturnUri});}
  public async beginMobileExchangeForSession(ownerUserId:string,creatorSessionId:string,pairingId:string,state:string,exchangeTransactionId:string,cleanupAfter:string,now:string):Promise<void>{
    const record=this.#records.get(pairingId);const supplied=Buffer.from(this.#digestAuthorizationState(state));const expected=Buffer.from(record?.authorizationStateHash??"");
    if(record===undefined||record.ownerUserId!==ownerUserId||record.creatorSessionId!==creatorSessionId||record.status!=="authorizing"||record.oauthFlow!=="mobile"||record.mobileCallbackClaimedAt===undefined||expected.length!==supplied.length||!timingSafeEqual(expected,supplied)||!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(exchangeTransactionId)||!Number.isFinite(Date.parse(cleanupAfter))||new Date(Date.parse(cleanupAfter)).toISOString()!==cleanupAfter||Date.parse(cleanupAfter)<=Date.parse(now))throw new DomainError("BROKER_AUTHORIZATION_EXCHANGE_INVALID","Broker authorization exchange could not be staged",400);
    record.mobileExchangeTransactionId=exchangeTransactionId;record.mobileExchangeCleanupAfter=cleanupAfter;record.mobileExchangeOperation="exchange_pending";
  }
  public async loadAuthorizationExchange(userId:string,exchangeTransactionId:string,_now:string):Promise<BrokerAuthorizationExchangeWork>{
    const record=[...this.#records.values()].find((candidate)=>candidate.ownerUserId===userId&&candidate.mobileExchangeTransactionId===exchangeTransactionId);
    if(record===undefined||record.mobileExchangeOperation===undefined||record.mobileExchangeCleanupAfter===undefined||this.approvedConnectorIdentity===undefined)throw new DomainError("BROKER_AUTHORIZATION_EXCHANGE_NOT_FOUND","Broker authorization exchange recovery operation was not found",404);
    return Object.freeze({userId,pairingId:record.pairingId,exchangeTransactionId,operation:record.mobileExchangeOperation,identity:this.approvedConnectorIdentity,cleanupAfter:record.mobileExchangeCleanupAfter});
  }
  public async requestAuthorizationExchangeRevocation(userId:string,exchangeTransactionId:string,_errorCode:string,_now:string):Promise<"revoke_pending"|"revoked"|"completed">{
    const record=[...this.#records.values()].find((candidate)=>candidate.ownerUserId===userId&&candidate.mobileExchangeTransactionId===exchangeTransactionId);
    if(record===undefined||record.mobileExchangeOperation===undefined)throw new DomainError("BROKER_AUTHORIZATION_EXCHANGE_NOT_FOUND","Broker authorization exchange recovery operation was not found",404);
    if(record.mobileExchangeOperation==="completed"||record.mobileExchangeOperation==="revoked")return record.mobileExchangeOperation;
    record.mobileExchangeOperation="revoke_pending";record.status="error";record.consumedAt=_now;delete record.authorizationStateHash;delete record.authorizationStateExpiresAt;delete record.oauthFlow;delete record.mobileState;delete record.mobileCodeVerifier;delete record.mobileNonce;delete record.mobileRedirectUri;delete record.mobileReturnUri;delete record.mobileCallbackClaimedAt;return "revoke_pending";
  }
  public async acknowledgeAuthorizationExchangeRevocation(userId:string,exchangeTransactionId:string,_now:string):Promise<"revoked"|"completed">{
    const record=[...this.#records.values()].find((candidate)=>candidate.ownerUserId===userId&&candidate.mobileExchangeTransactionId===exchangeTransactionId);
    if(record===undefined||record.mobileExchangeOperation===undefined)throw new DomainError("BROKER_AUTHORIZATION_EXCHANGE_NOT_FOUND","Broker authorization exchange recovery operation was not found",404);
    if(record.mobileExchangeOperation==="completed")return "completed";if(record.mobileExchangeOperation==="revoked")return "revoked";if(record.mobileExchangeOperation!=="revoke_pending")throw new DomainError("BROKER_AUTHORIZATION_EXCHANGE_INVALID","Broker authorization exchange revocation cannot be acknowledged",409);record.mobileExchangeOperation="revoked";return "revoked";
  }
  public async completeMobileForSession(ownerUserId:string,creatorSessionId:string,pairingId:string,state:string,exchangeTransactionId:string,provisionalCredentialExpiresAt:string,completion:BrokerConnectionSummary|BrokerAuthorizationCompletion,now:string):Promise<{readonly authorizationSagaId:string}>{const record=this.#records.get(pairingId);const supplied=Buffer.from(this.#digestAuthorizationState(state));const expected=Buffer.from(record?.authorizationStateHash??"");if(record===undefined||record.ownerUserId!==ownerUserId||record.creatorSessionId!==creatorSessionId||record.status!=="authorizing"||record.oauthFlow!=="mobile"||record.mobileCallbackClaimedAt===undefined||expected.length!==supplied.length||!timingSafeEqual(expected,supplied)||record.mobileExchangeOperation!=="exchange_pending"||record.mobileExchangeTransactionId!==exchangeTransactionId||record.mobileExchangeCleanupAfter===undefined||Date.parse(record.mobileExchangeCleanupAfter)<=Date.parse(now)||!Number.isFinite(Date.parse(provisionalCredentialExpiresAt))||new Date(Date.parse(provisionalCredentialExpiresAt)).toISOString()!==provisionalCredentialExpiresAt||!("credentialHandle" in completion)||!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(exchangeTransactionId)||Date.parse(provisionalCredentialExpiresAt)<=Date.parse(now))throw new DomainError("PAIRING_INVALID","Pairing callback is invalid or expired",400);if([...this.#records.values()].some((candidate)=>candidate!==record&&(candidate.mobileExchangeTransactionId===exchangeTransactionId||candidate.mobileCredentialHandle===completion.credentialHandle)))throw new DomainError("BROKER_AUTHORIZATION_BINDING_REUSED","Broker authorization binding was already used",409);record.status="authorizing";record.connection=Object.freeze({status:"pending",capabilities:Object.freeze([]),equityTradingAvailable:false,optionsTradingAvailable:false});record.mobileCredentialHandle=completion.credentialHandle;record.mobileAuthorizationSagaId=randomUUID();record.mobileExchangeOperation="completed";record.mobileConfirmationDeadlineAt=provisionalCredentialExpiresAt;record.mobileSagaOperation="confirm_pending";record.mobileSagaIdentity=completion.identity;record.mobileCompletion=completion;record.consumedAt=now;record.codeDisplay="";delete record.authorizationStateHash;delete record.authorizationStateExpiresAt;delete record.oauthFlow;delete record.mobileState;delete record.mobileNonce;delete record.mobileRedirectUri;delete record.mobileReturnUri;delete record.mobileCallbackClaimedAt;return Object.freeze({authorizationSagaId:record.mobileAuthorizationSagaId});}
  public async loadAuthorizationSaga(userId:string,sagaId:string,_now:string):Promise<BrokerAuthorizationSagaWork>{const record=[...this.#records.values()].find((candidate)=>candidate.ownerUserId===userId&&candidate.mobileAuthorizationSagaId===sagaId);if(record===undefined||record.mobileExchangeTransactionId===undefined||record.mobileConfirmationDeadlineAt===undefined||record.mobileSagaOperation===undefined||record.mobileSagaIdentity===undefined)throw new DomainError("BROKER_AUTHORIZATION_SAGA_NOT_FOUND","Broker authorization recovery operation was not found",404);return Object.freeze({sagaId,userId,pairingId:record.pairingId,connectionId:record.pairingId,exchangeTransactionId:record.mobileExchangeTransactionId,operation:record.mobileSagaOperation,identity:record.mobileSagaIdentity,confirmationDeadlineAt:record.mobileConfirmationDeadlineAt,...(record.mobileCompletion===undefined?{}:{completion:record.mobileCompletion})});}
  public async requestAuthorizationRevocation(userId:string,sagaId:string,_errorCode:string,_now:string):Promise<"revoke_pending"|"revoked">{const record=[...this.#records.values()].find((candidate)=>candidate.ownerUserId===userId&&candidate.mobileAuthorizationSagaId===sagaId);if(record===undefined||record.mobileSagaOperation===undefined)throw new DomainError("BROKER_AUTHORIZATION_SAGA_NOT_FOUND","Broker authorization recovery operation was not found",404);if(record.mobileSagaOperation==="revoked")return "revoked";record.mobileSagaOperation="revoke_pending";record.status="error";delete record.mobileCredentialHandle;delete record.mobileCredentialConfirmedAt;delete record.connection;return "revoke_pending";}
  public async acknowledgeAuthorizationConfirmation(userId:string,sagaId:string,now:string):Promise<BrokerAuthorizationSagaOperation>{
    const record=[...this.#records.values()].find((candidate)=>candidate.ownerUserId===userId&&candidate.mobileAuthorizationSagaId===sagaId);
    if(record===undefined||record.mobileSagaOperation===undefined)throw new DomainError("BROKER_AUTHORIZATION_SAGA_NOT_FOUND","Broker authorization recovery operation was not found",404);
    if(record.mobileSagaOperation==="confirm_pending"&&Date.parse(record.mobileConfirmationDeadlineAt??"")<=Date.parse(now)){
      await this.requestAuthorizationRevocation(userId,sagaId,"AUTHORIZATION_CONFIRMATION_DEADLINE_EXCEEDED",now);
      return "revoke_pending";
    }
    if(record.mobileSagaOperation==="confirm_pending"){record.mobileSagaOperation="confirmed";record.mobileCredentialConfirmedAt=now;}
    return record.mobileSagaOperation;
  }
  public async acknowledgeAuthorizationRevocation(userId:string,sagaId:string,_now:string):Promise<"revoked">{const record=[...this.#records.values()].find((candidate)=>candidate.ownerUserId===userId&&candidate.mobileAuthorizationSagaId===sagaId);if(record===undefined||record.mobileSagaOperation===undefined)throw new DomainError("BROKER_AUTHORIZATION_SAGA_NOT_FOUND","Broker authorization recovery operation was not found",404);if(record.mobileSagaOperation==="revoked")return "revoked";if(record.mobileSagaOperation!=="revoke_pending")throw new DomainError("BROKER_AUTHORIZATION_SAGA_INVALID","Broker authorization revocation cannot be acknowledged",409);record.mobileSagaOperation="revoked";record.status="error";delete record.mobileCredentialHandle;delete record.mobileCredentialConfirmedAt;delete record.mobileCompletion;delete record.connection;return "revoked";}
  public async authorizationRevocationTarget(ownerUserId:string,_now:string):Promise<BrokerAuthorizationRevocationTarget>{
    const records=[...this.#records.values()].filter((candidate)=>candidate.ownerUserId===ownerUserId);
    const sagas=records.filter((candidate)=>candidate.mobileAuthorizationSagaId!==undefined&&candidate.mobileSagaOperation!==undefined&&candidate.mobileSagaOperation!=="revoked");
    if(sagas.length>1)throw new DomainError("BROKER_AUTHORIZATION_BINDING_INVALID","More than one active broker authorization was found",500);
    const saga=sagas[0];if(saga?.mobileAuthorizationSagaId!==undefined)return Object.freeze({kind:"saga",authorizationSagaId:saga.mobileAuthorizationSagaId});
    const exchanges=records.filter((candidate)=>candidate.mobileExchangeTransactionId!==undefined&&(candidate.mobileExchangeOperation==="exchange_pending"||candidate.mobileExchangeOperation==="revoke_pending"));
    if(exchanges.length>1)throw new DomainError("BROKER_AUTHORIZATION_BINDING_INVALID","More than one active broker exchange was found",500);
    const exchange=exchanges[0];if(exchange?.mobileExchangeTransactionId!==undefined)return Object.freeze({kind:"exchange",exchangeTransactionId:exchange.mobileExchangeTransactionId});
    if(records.some((candidate)=>candidate.mobileExchangeOperation==="completed"&&candidate.mobileAuthorizationSagaId===undefined))return Object.freeze({kind:"unmanaged"});
    if(records.some((candidate)=>candidate.connection!==undefined))return Object.freeze({kind:"demo"});
    return Object.freeze({kind:"none"});
  }
  public async disconnectDemoAuthorization(ownerUserId:string,now:string):Promise<void>{
    const records=[...this.#records.values()].filter((candidate)=>candidate.ownerUserId===ownerUserId);
    if(records.some((candidate)=>(candidate.mobileSagaOperation!==undefined&&candidate.mobileSagaOperation!=="revoked")||(candidate.mobileExchangeOperation!==undefined&&!['completed','revoked'].includes(candidate.mobileExchangeOperation))))throw new DomainError("BROKER_REVOCATION_REQUIRED","Provider-backed authorization cannot be cleared as Demo state",409);
    for(const record of records){if(record.connection===undefined)continue;record.status="canceled";record.consumedAt=now;record.codeDisplay="";delete record.connection;}
  }
  public async concludeMobileWithoutConnection(ownerUserId:string,creatorSessionId:string,pairingId:string,state:string,outcome:"canceled"|"error",now:string):Promise<void>{const record=this.#records.get(pairingId);const supplied=Buffer.from(this.#digestAuthorizationState(state));const expected=Buffer.from(record?.authorizationStateHash??"");if(record===undefined||record.ownerUserId!==ownerUserId||record.creatorSessionId!==creatorSessionId||record.status!=="authorizing"||record.oauthFlow!=="mobile"||record.mobileCallbackClaimedAt===undefined||expected.length!==supplied.length||!timingSafeEqual(expected,supplied))throw new DomainError("PAIRING_INVALID","Pairing callback is invalid or expired",400);record.status=outcome==="canceled"?"pending":"error";if(outcome==="error")record.consumedAt=now;delete record.authorizationStateHash;delete record.authorizationStateExpiresAt;delete record.oauthFlow;delete record.mobileState;delete record.mobileNonce;delete record.mobileRedirectUri;delete record.mobileReturnUri;delete record.mobileCallbackClaimedAt;}
  public healthy():boolean{return true;}
}
