import { createHash, createHmac, randomBytes, randomUUID, timingSafeEqual } from "node:crypto";
import { DomainError } from "@whox/contracts";
import { PostgresTenantDatabase } from "./database.js";
import type { AccessClaims, AuthTokens, SessionService } from "./security.js";

const encode=(value:unknown):string=>Buffer.from(JSON.stringify(value)).toString("base64url");
const digest=(value:string):string=>createHash("sha256").update(value).digest("hex");
const uuidPattern=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const iso=(value:string|null):string|null=>value===null?null:new Date(value).toISOString();

export class PostgresSessionService implements SessionService {
  public readonly persistenceKind="persistent" as const;
  public constructor(private readonly database:PostgresTenantDatabase,private readonly signingKey:Buffer){if(signingKey.length<32)throw new TypeError("SESSION_SIGNING_SECRET must contain at least 32 bytes");}
  #sign(data:string):string{return createHmac("sha256",this.signingKey).update(data).digest("base64url");}
  #deviceDigest(deviceId:string):string{return createHmac("sha256",this.signingKey).update(`device:${deviceId}`).digest("hex");}
  #jwt(claims:AccessClaims):string{const data=`${encode({alg:"HS256",typ:"JWT"})}.${encode(claims)}`;return `${data}.${this.#sign(data)}`;}
  #tokens(userId:string,sessionId:string,deviceId:string,now:Date):{readonly response:AuthTokens;readonly refreshDigest:string}{const accessExp=new Date(now.getTime()+15*60_000);const refreshExp=new Date(now.getTime()+30*24*60*60_000);const refreshToken=`${userId}.${Buffer.from(deviceId,"utf8").toString("base64url")}.${randomBytes(48).toString("base64url")}`;return Object.freeze({refreshDigest:digest(refreshToken),response:Object.freeze({accessToken:this.#jwt({sub:userId,sessionId,deviceId,iat:Math.floor(now.getTime()/1000),exp:Math.floor(accessExp.getTime()/1000),kind:"access"}),accessExpiresAt:accessExp.toISOString(),refreshToken,refreshExpiresAt:refreshExp.toISOString(),sessionId})});}
  #parseClaims(accessToken:string,now:Date):AccessClaims{const parts=accessToken.split(".");if(parts.length!==3)throw new DomainError("AUTH_INVALID","Session token is invalid",401);const data=`${parts[0]}.${parts[1]}`;const expected=Buffer.from(this.#sign(data));const received=Buffer.from(parts[2]!);if(expected.length!==received.length||!timingSafeEqual(expected,received))throw new DomainError("AUTH_INVALID","Session token is invalid",401);let header:unknown;let claims:unknown;try{header=JSON.parse(Buffer.from(parts[0]!,"base64url").toString("utf8"));claims=JSON.parse(Buffer.from(parts[1]!,"base64url").toString("utf8"));}catch{throw new DomainError("AUTH_INVALID","Session token is invalid",401);}if(typeof header!=="object"||header===null||(header as Record<string,unknown>).alg!=="HS256"||(header as Record<string,unknown>).typ!=="JWT"||typeof claims!=="object"||claims===null)throw new DomainError("AUTH_INVALID","Session token is invalid",401);const candidate=claims as Record<string,unknown>;if(typeof candidate.sub!=="string"||!uuidPattern.test(candidate.sub)||typeof candidate.sessionId!=="string"||!uuidPattern.test(candidate.sessionId)||typeof candidate.deviceId!=="string"||typeof candidate.iat!=="number"||typeof candidate.exp!=="number"||candidate.kind!=="access"||!Number.isInteger(candidate.iat)||!Number.isInteger(candidate.exp))throw new DomainError("AUTH_INVALID","Session token claims are invalid",401);const typed=candidate as unknown as AccessClaims;const nowSeconds=Math.floor(now.getTime()/1000);if(typed.exp<=nowSeconds||typed.iat>nowSeconds+30||typed.exp-typed.iat>15*60)throw new DomainError("AUTH_EXPIRED","Session is expired or revoked",401);return Object.freeze(typed);}
  public async create(userId:string,deviceId:string,now=new Date()):Promise<AuthTokens>{const sessionId=randomUUID();const issued=this.#tokens(userId,sessionId,deviceId,now);await this.database.withTenant(userId,async(transaction)=>{const device=await transaction.query<{id:string}>(`INSERT INTO devices(user_id,platform,device_name,client_identifier_digest,last_seen_at)
        VALUES($1,'ios','iOS device',$2,$3)
        ON CONFLICT (user_id,client_identifier_digest) WHERE client_identifier_digest IS NOT NULL AND revoked_at IS NULL
        DO UPDATE SET last_seen_at=EXCLUDED.last_seen_at
        RETURNING id::text`,[userId,this.#deviceDigest(deviceId),now.toISOString()]);const deviceRow=device.rows[0];if(deviceRow===undefined)throw new DomainError("DEVICE_PERSISTENCE_FAILED","Device could not be persisted",500);await transaction.query(`INSERT INTO sessions(id,user_id,device_id,refresh_token_digest,created_at,last_used_at,expires_at,rotation_counter)
        VALUES($1,$2,$3,$4,$5,$5,$6,0)`,[sessionId,userId,deviceRow.id,issued.refreshDigest,now.toISOString(),issued.response.refreshExpiresAt]);});return issued.response;}
  public async verify(accessToken:string,now=new Date()):Promise<AccessClaims>{const claims=this.#parseClaims(accessToken,now);const valid=await this.database.withTenant(claims.sub,async(transaction)=>{const result=await transaction.query<{valid:boolean}>(`SELECT EXISTS(
          SELECT 1 FROM sessions s JOIN devices d ON d.id=s.device_id AND d.user_id=s.user_id
          WHERE s.id=$1 AND s.user_id=$2 AND s.revoked_at IS NULL AND s.expires_at>$3
            AND d.revoked_at IS NULL AND d.client_identifier_digest=$4
        ) AS valid`,[claims.sessionId,claims.sub,now.toISOString(),this.#deviceDigest(claims.deviceId)]);return result.rows[0]?.valid===true;});if(!valid)throw new DomainError("AUTH_EXPIRED","Session is expired or revoked",401);return claims;}
  public async rotate(sessionId:string,refreshToken:string,now=new Date()):Promise<AuthTokens>{const parts=refreshToken.split(".");const userId=parts[0]??"";let deviceId="";try{deviceId=Buffer.from(parts[1]??"","base64url").toString("utf8");}catch{throw new DomainError("REFRESH_INVALID","Refresh token is invalid",401);}if(parts.length!==3||!uuidPattern.test(userId)||!uuidPattern.test(sessionId)||!/^[A-Za-z0-9._:-]{1,200}$/.test(deviceId))throw new DomainError("REFRESH_INVALID","Refresh token is invalid",401);const outcome=await this.database.withTenant(userId,async(transaction)=>{await transaction.query("SELECT id FROM users WHERE id=$1 FOR UPDATE",[userId]);const result=await transaction.query<{refresh_token_digest:string;expires_at:string;revoked_at:string|null;device_digest:string|null;device_id:string|null}>(`SELECT s.refresh_token_digest,s.expires_at::text,s.revoked_at::text,d.client_identifier_digest AS device_digest,d.id::text AS device_id
          FROM sessions s LEFT JOIN devices d ON d.id=s.device_id AND d.user_id=s.user_id
          WHERE s.id=$1 AND s.user_id=$2 FOR UPDATE OF s`,[sessionId,userId]);const row=result.rows[0];if(row===undefined||row.revoked_at!==null||Date.parse(row.expires_at)<=now.getTime()||row.device_digest!==this.#deviceDigest(deviceId))return {kind:"invalid" as const};const expected=Buffer.from(row.refresh_token_digest);const actual=Buffer.from(digest(refreshToken));if(expected.length!==actual.length||!timingSafeEqual(expected,actual)){const revokedAt=now.toISOString();if(row.device_id!==null){await transaction.query("UPDATE sessions SET revoked_at=COALESCE(revoked_at,$3),last_used_at=$3 WHERE user_id=$1 AND device_id=$2",[userId,row.device_id,revokedAt]);await transaction.query("UPDATE device_tokens SET invalidated_at=COALESCE(invalidated_at,$3) WHERE user_id=$1 AND device_id=$2",[userId,row.device_id,revokedAt]);await transaction.query("UPDATE devices SET revoked_at=COALESCE(revoked_at,$3) WHERE user_id=$1 AND id=$2",[userId,row.device_id,revokedAt]);}else await transaction.query("UPDATE sessions SET revoked_at=COALESCE(revoked_at,$3),last_used_at=$3 WHERE id=$1 AND user_id=$2",[sessionId,userId,revokedAt]);return {kind:"replay" as const};}const issued=this.#tokens(userId,sessionId,deviceId,now);await transaction.query(`UPDATE sessions SET refresh_token_digest=$3,last_used_at=$4,expires_at=$5,rotation_counter=rotation_counter+1 WHERE id=$1 AND user_id=$2`,[sessionId,userId,issued.refreshDigest,now.toISOString(),issued.response.refreshExpiresAt]);return {kind:"issued" as const,tokens:issued.response};});if(outcome.kind==="replay")throw new DomainError("REFRESH_REPLAYED","Refresh token is invalid or already rotated; the device and its sessions were revoked",401);if(outcome.kind!=="issued")throw new DomainError("REFRESH_INVALID","Refresh token is invalid",401);return outcome.tokens;}
  public async revoke(sessionId:string,now=new Date(),userId?:string):Promise<void>{if(userId===undefined||!uuidPattern.test(userId))throw new DomainError("TENANT_CONTEXT_INVALID","Authenticated tenant context is required to revoke a session",401);await this.database.withTenant(userId,async(transaction)=>{await transaction.query("SELECT id FROM users WHERE id=$1 FOR UPDATE",[userId]);const result=await transaction.query<{deviceId:string|null}>("SELECT device_id::text AS \"deviceId\" FROM sessions WHERE id=$1 AND user_id=$2 FOR UPDATE",[sessionId,userId]);const deviceId=result.rows[0]?.deviceId;if(deviceId===undefined)return;const revokedAt=now.toISOString();if(deviceId===null){await transaction.query("UPDATE sessions SET revoked_at=COALESCE(revoked_at,$3),last_used_at=$3 WHERE id=$1 AND user_id=$2",[sessionId,userId,revokedAt]);return;}await transaction.query("UPDATE sessions SET revoked_at=COALESCE(revoked_at,$3),last_used_at=$3 WHERE user_id=$1 AND device_id=$2",[userId,deviceId,revokedAt]);await transaction.query("UPDATE device_tokens SET invalidated_at=COALESCE(invalidated_at,$3) WHERE user_id=$1 AND device_id=$2",[userId,deviceId,revokedAt]);await transaction.query("UPDATE devices SET revoked_at=COALESCE(revoked_at,$3) WHERE user_id=$1 AND id=$2",[userId,deviceId,revokedAt]);});}
  public async list(userId:string):Promise<readonly Readonly<Record<string,unknown>>[]>{return await this.database.withTenant(userId,async(transaction)=>{const result=await transaction.query<{sessionId:string;deviceId:string;createdAt:string;lastUsedAt:string|null;refreshExpiresAt:string;revokedAt:string|null}>(`SELECT s.id::text AS "sessionId",d.public_identifier::text AS "deviceId",s.created_at::text AS "createdAt",s.last_used_at::text AS "lastUsedAt",s.expires_at::text AS "refreshExpiresAt",s.revoked_at::text AS "revokedAt" FROM sessions s LEFT JOIN devices d ON d.id=s.device_id AND d.user_id=s.user_id WHERE s.user_id=$1 ORDER BY s.created_at DESC`,[userId]);return Object.freeze(result.rows.map((row)=>Object.freeze({...row,createdAt:iso(row.createdAt),lastUsedAt:iso(row.lastUsedAt),refreshExpiresAt:iso(row.refreshExpiresAt),revokedAt:iso(row.revokedAt)})));});}
  public async healthy():Promise<boolean>{return await this.database.ready();}
}
