import { randomUUID } from "node:crypto";
import { AGENT_CATALOG } from "@whox/agent-definitions";
import { DomainError, type Entitlements, type PlanAgentAssignment, type RiskPolicy, type SubscriptionPlanCatalog } from "@whox/contracts";
import { DEMO_ACCOUNT_ID, DEMO_EQUITY_PROPOSAL, DEMO_RISK_POLICY, DEMO_USER_ID, FIXTURE_NOW } from "@whox/test-fixtures";
import { LEGAL_DOCUMENTS, assessEligibility, evaluateRiskAssessment, validateLegalConsentVersions, type EligibilityRecord, type LegalConsentRecord, type RiskAssessmentRecord } from "./compliance.js";
import type { VerifiedStepUpAuthentication } from "./step-up.js";
import type { VerifiedStoreKitTransaction } from "./storekit.js";

export interface UserRecord {readonly userId:string;name:string;email:string;readonly status:"active"|"suspended"|"closed";onboardingStep:number;accountMode:"demo"|"paper"|"live";}
export interface UserAgentRecord {readonly id:string;readonly userId:string;readonly agentId:string;status:"monitoring"|"paused";allocation:number;approvalMode:"observe"|"confirm_every_trade"|"automatic_within_limits";configurationVersion:number;configuration:Readonly<Record<string,unknown>>;readonly createdAt:string;updatedAt:string;}
export interface ProposalRecord {readonly id:string;readonly userId:string;status:string;readonly proposal:typeof DEMO_EQUITY_PROPOSAL;updatedAt:string;}
export interface OrderFillRecord {readonly id:string;readonly timestamp:string;readonly quantity:number;readonly price:number;readonly fees:number|null;}
export interface OrderTimelineRecord {readonly status:string;readonly occurredAt:string;readonly reasonCode:string|null;}
export interface OrderRecord {readonly id:string;readonly userId:string;readonly proposalId:string;readonly status:string;readonly symbol:string;readonly side:"buy"|"sell";readonly quantity:number;readonly filledQuantity:number;readonly remainingQuantity:number;readonly averageFillPrice:number|null;readonly brokerOrderId:string|null;readonly instrumentType:"equity"|"option";readonly orderType:string;readonly limitPrice:number|null;readonly timeInForce:string;readonly submittedAt:string|null;readonly terminalAt:string|null;readonly statusReason:string|null;readonly reconciliationStatus:string;readonly fills:readonly OrderFillRecord[];readonly auditTimeline:readonly OrderTimelineRecord[];readonly mode:"demo"|"paper";readonly dataClassification:"demo"|"paper";readonly updatedAt:string;}
export interface NotificationRecord {readonly id:string;readonly userId:string;readonly type:string;readonly title:string;readonly createdAt:string;readAt?:string;}
export interface ApprovalRecord {readonly id:string;readonly userId:string;readonly proposalId:string;readonly status:"approved";readonly approvingDeviceId:string;readonly sessionId:string;readonly authenticationMethod:VerifiedStepUpAuthentication["method"];readonly authenticationVerificationId:string;readonly authenticatedAt:string;readonly approvedAt:string;readonly idempotencyKey:string;}
const LEGAL_DOCUMENT_TITLES:Readonly<Record<string,string>>=Object.freeze({terms:"Terms of Service",privacy:"Privacy Policy","ai-risk":"AI Agent Risk Disclosure",broker:"Brokerage Connection Disclosure",options:"Options Risk Disclosure",subscription:"Subscription Terms",advisory:"Investment Advisory Agreement",electronic:"Electronic Communications Consent",performance:"Performance Presentation Disclosure","ai-data":"Data Processing and Third-Party AI Disclosure"});

const DEFAULT_RESEARCH_UNIVERSE=Object.freeze(["AAPL","MSFT","VTI"] as const);
const planAgentAssignments=(agentIds:readonly string[]):readonly PlanAgentAssignment[]=>Object.freeze(agentIds.map((agentId,index)=>{const definition=AGENT_CATALOG.find((item)=>item.agentId===agentId);if(definition===undefined)throw new Error(`Plan references unknown agent ${agentId}`);return Object.freeze({agentId,displayName:definition.displayName,agentVersion:definition.version,catalogPosition:(index+1) as 1|2|3,releaseStatus:definition.status,deterministicStrategyVersion:definition.deterministicStrategyVersion,researchUniverse:Object.freeze([...DEFAULT_RESEARCH_UNIVERSE])});}));
const planCatalog=(id:string,name:string,productId:string,features:Omit<Entitlements,"agentCatalog">,agentIds:readonly string[]):SubscriptionPlanCatalog=>{if(agentIds.length<1||agentIds.length>3||new Set(agentIds).size!==agentIds.length)throw new Error(`Plan ${id} must reference one to three distinct agents`);return Object.freeze({id,name,productId,features:Object.freeze({...features,agentCatalog:Object.freeze([...agentIds])}),agentCatalogVersion:1,agents:planAgentAssignments(agentIds)});};

export const PLANS:readonly SubscriptionPlanCatalog[]=Object.freeze([
  planCatalog("equity","Equity","ai.whox.yield.equity.monthly",{stockTrading:true,optionsTrading:false,multiLegOptions:false,maximumActiveAgents:1,automaticMode:false,monitoringFrequencyMinutes:1440,advancedAnalytics:false,customWatchlists:false,scannerAccess:false,prioritySupport:false},["foundation-equity"]),
  planCatalog("equity_pro","Equity Pro","ai.whox.yield.equitypro.monthly",{stockTrading:true,optionsTrading:false,multiLegOptions:false,maximumActiveAgents:3,automaticMode:true,monitoringFrequencyMinutes:30,advancedAnalytics:true,customWatchlists:true,scannerAccess:true,prioritySupport:true},["foundation-equity","equity-momentum","quality-swing"]),
  planCatalog("options","Options","ai.whox.yield.options.monthly",{stockTrading:true,optionsTrading:true,multiLegOptions:false,maximumActiveAgents:3,automaticMode:true,monitoringFrequencyMinutes:30,advancedAnalytics:true,customWatchlists:true,scannerAccess:true,prioritySupport:true},["foundation-equity","directional-options","covered-strategy"]),
  planCatalog("options_pro","Options Pro","ai.whox.yield.optionspro.monthly",{stockTrading:true,optionsTrading:true,multiLegOptions:true,maximumActiveAgents:3,automaticMode:true,monitoringFrequencyMinutes:15,advancedAnalytics:true,customWatchlists:true,scannerAccess:true,prioritySupport:true},["foundation-equity","defined-risk-spreads","range-volatility"])
]);

export class MemoryDataStore {
  public readonly persistenceKind:"ephemeral"|"persistent"="ephemeral";
  readonly #users=new Map<string,UserRecord>();readonly #appleSubjects=new Map<string,string>();readonly #agents=new Map<string,UserAgentRecord>();
  readonly #proposals=new Map<string,ProposalRecord>();readonly #orders=new Map<string,OrderRecord>();readonly #notifications=new Map<string,NotificationRecord>();
  readonly #riskPolicies=new Map<string,RiskPolicy>();readonly #idempotency=new Map<string,{readonly fingerprint:string;readonly value:unknown}>();readonly #supportTickets=new Map<string,unknown>();
  readonly #subscriptionPlans=new Map<string,string>();
  readonly #settings=new Map<string,Readonly<Record<string,unknown>>>();
  readonly #eligibility=new Map<string,EligibilityRecord>();readonly #riskAssessments=new Map<string,RiskAssessmentRecord>();readonly #legalConsents=new Map<string,LegalConsentRecord>();
  readonly #approvals=new Map<string,ApprovalRecord>();readonly #usedStepUpVerificationIds=new Set<string>();
  readonly #consumedAppleAssertions=new Set<string>();
  public constructor(){this.seedDemo();}
  public seedDemo():void{if(this.#users.has(DEMO_USER_ID))return;this.#users.set(DEMO_USER_ID,{userId:DEMO_USER_ID,name:"Treasury Reviewer",email:"review@whox.example",status:"active",onboardingStep:14,accountMode:"demo"});this.#appleSubjects.set("demo.apple.subject",DEMO_USER_ID);this.#riskPolicies.set(DEMO_USER_ID,DEMO_RISK_POLICY);this.#subscriptionPlans.set(DEMO_USER_ID,"equity");
    this.#eligibility.set(DEMO_USER_ID,assessEligibility({country:"US",region:"NY",ageEligible:true,individualAccount:true,understandsNotBankOrBroker:true,adviserClientClassification:"selfDirected"},"12000000-0000-4000-8000-000000000001",DEMO_USER_ID,FIXTURE_NOW));
    this.#riskAssessments.set(DEMO_USER_ID,evaluateRiskAssessment({objective:"Long-term growth",holdingPeriod:"3-5 years",tradingExperience:"Some experience",stockExperience:"Some experience",optionsExperience:"None",lossTolerance:15,dependsOnFunds:false,liquidityNeed:"Moderate",volatilityComfort:"Some",confirmationPreference:"Confirm every trade",understandsOptionsPremiumLoss:false,investorProfileAcknowledged:true},"13000000-0000-4000-8000-000000000001",DEMO_USER_ID,FIXTURE_NOW));
    for(const document of LEGAL_DOCUMENTS)this.#legalConsents.set(`${DEMO_USER_ID}:${document.key}:${document.version}`,Object.freeze({id:randomUUID(),userId:DEMO_USER_ID,documentKey:document.key,documentVersion:document.version,acceptedAt:FIXTURE_NOW,sessionId:"demo-seeded-session",deviceId:"demo-seeded-device"}));
    const agent:UserAgentRecord={id:"60000000-0000-4000-8000-000000000001",userId:DEMO_USER_ID,agentId:"foundation-equity",status:"monitoring",allocation:0.4,approvalMode:"confirm_every_trade",configurationVersion:1,configuration:Object.freeze({symbol:"MSFT",targetOrderAmount:1000}),createdAt:FIXTURE_NOW,updatedAt:FIXTURE_NOW};this.#agents.set(agent.id,agent);
    this.#proposals.set(DEMO_EQUITY_PROPOSAL.proposalId,{id:DEMO_EQUITY_PROPOSAL.proposalId,userId:DEMO_USER_ID,status:"AWAITING_USER_APPROVAL",proposal:DEMO_EQUITY_PROPOSAL,updatedAt:FIXTURE_NOW});
    const demoFillPrice=DEMO_EQUITY_PROPOSAL.limitPrice??DEMO_EQUITY_PROPOSAL.notionalEstimate/DEMO_EQUITY_PROPOSAL.quantity;
    const order:OrderRecord={id:"70000000-0000-4000-8000-000000000001",userId:DEMO_USER_ID,proposalId:DEMO_EQUITY_PROPOSAL.proposalId,status:"FILLED",symbol:DEMO_EQUITY_PROPOSAL.symbol,side:DEMO_EQUITY_PROPOSAL.side,quantity:2,filledQuantity:2,remainingQuantity:0,averageFillPrice:demoFillPrice,brokerOrderId:"demo-order-filled-1",instrumentType:DEMO_EQUITY_PROPOSAL.instrumentType,orderType:DEMO_EQUITY_PROPOSAL.orderType,limitPrice:DEMO_EQUITY_PROPOSAL.limitPrice??null,timeInForce:DEMO_EQUITY_PROPOSAL.timeInForce,submittedAt:FIXTURE_NOW,terminalAt:FIXTURE_NOW,statusReason:null,reconciliationStatus:"reconciled",fills:Object.freeze([{id:"demo-fill-1",timestamp:FIXTURE_NOW,quantity:2,price:demoFillPrice,fees:0}]),auditTimeline:Object.freeze([{status:"FILLED",occurredAt:FIXTURE_NOW,reasonCode:null}]),mode:"demo",dataClassification:"demo",updatedAt:FIXTURE_NOW};this.#orders.set(order.id,order);
    const notification:NotificationRecord={id:"80000000-0000-4000-8000-000000000001",userId:DEMO_USER_ID,type:"proposal_ready",title:"Demo proposal ready to review",createdAt:FIXTURE_NOW};this.#notifications.set(notification.id,notification);
  }
  public userForAppleSubject(subject:string,email?:string):UserRecord{const existing=this.#appleSubjects.get(subject);if(existing!==undefined)return this.#users.get(existing)!;const id=randomUUID();const user:UserRecord={userId:id,name:"Treasury User",email:email??"",status:"active",onboardingStep:1,accountMode:"demo"};this.#users.set(id,user);this.#appleSubjects.set(subject,id);this.#riskPolicies.set(id,{...DEMO_RISK_POLICY,policyId:randomUUID(),userId:id,updatedAt:new Date().toISOString()});this.#subscriptionPlans.set(id,"equity");return user;}
  public consumeAppleIdentityAssertion(assertionDigest:string,_expiresAt:string,_consumedAt:string):void{if(this.#consumedAppleAssertions.has(assertionDigest))throw new DomainError("APPLE_IDENTITY_REPLAYED","Apple identity token was already consumed",401);this.#consumedAppleAssertions.add(assertionDigest);}
  public consumeStepUpAuthentication(userId:string,verification:VerifiedStepUpAuthentication,_usedAt:string):void{this.getUser(userId);if(verification.userId!==userId)throw new DomainError("STEP_UP_CONTEXT_MISMATCH","The verified authentication proof belongs to another user",403);if(this.#usedStepUpVerificationIds.has(verification.verificationId))throw new DomainError("STEP_UP_PROOF_REPLAYED","The authentication proof was already used",409);this.#usedStepUpVerificationIds.add(verification.verificationId);}
  public getUser(userId:string):UserRecord{const user=this.#users.get(userId);if(user===undefined)throw new DomainError("USER_NOT_FOUND","User was not found",404);return user;}
  public patchUser(userId:string,input:Readonly<Record<string,unknown>>):UserRecord{const user=this.getUser(userId);if(typeof input.name==="string"&&input.name.trim()!=="")user.name=input.name.trim();if(input.accountMode!==undefined&&input.accountMode!=="demo")throw new DomainError("PERSISTENT_MARKET_DATA_REQUIRED","The in-memory Demo store cannot represent Paper or Live account data",503);user.accountMode="demo";return user;}
  public onboarding(userId:string):Readonly<Record<string,unknown>>{const user=this.getUser(userId);const eligibility=this.#eligibility.get(userId);const legalConsentsComplete=this.hasAllRequiredLegalConsents(userId);const completed=user.onboardingStep>=14&&eligibility?.status==="eligible"&&this.#riskAssessments.has(userId)&&legalConsentsComplete;return Object.freeze({currentStep:user.onboardingStep,completed,resumable:true,eligibilityStatus:eligibility?.status??"not_assessed",riskAssessmentStatus:this.#riskAssessments.has(userId)?"current":"not_assessed",legalConsentsComplete});}
  public updateOnboarding(userId:string,step:number):Readonly<Record<string,unknown>>{const user=this.getUser(userId);if(!Number.isInteger(step)||step<1||step>14)throw new DomainError("ONBOARDING_STEP_INVALID","Onboarding step must be between 1 and 14",400);if(step>=4)this.requireEligible(userId);if(step>=6&&!this.#riskAssessments.has(userId))throw new DomainError("RISK_ASSESSMENT_REQUIRED","A current risk assessment is required before onboarding can continue",409);if(step>=14&&!this.hasAllRequiredLegalConsents(userId))throw new DomainError("LEGAL_CONSENTS_REQUIRED","Every required current legal-document version must be accepted before onboarding can be completed",409);user.onboardingStep=Math.max(user.onboardingStep,step);return this.onboarding(userId);}
  public eligibility(userId:string):EligibilityRecord|undefined{this.getUser(userId);return this.#eligibility.get(userId);}
  public recordEligibility(userId:string,input:Readonly<Record<string,unknown>>,recordedAt:string):EligibilityRecord{const account=this.getUser(userId);const record=assessEligibility(input,randomUUID(),userId,recordedAt);this.#eligibility.set(userId,record);if(record.status!=="eligible")account.onboardingStep=Math.min(account.onboardingStep,3);return record;}
  public requireEligible(userId:string):EligibilityRecord{const record=this.eligibility(userId);if(record===undefined)throw new DomainError("ELIGIBILITY_REQUIRED","An eligibility assessment is required before onboarding can continue",409);if(record.status!=="eligible")throw new DomainError("ELIGIBILITY_NOT_APPROVED","Eligibility is ineligible or requires review",409,{status:record.status,reasons:record.reasons});return record;}
  public createRiskAssessment(userId:string,input:Readonly<Record<string,unknown>>,recordedAt:string):RiskAssessmentRecord{this.requireEligible(userId);const record=evaluateRiskAssessment(input,randomUUID(),userId,recordedAt);this.#riskAssessments.set(userId,record);return record;}
  public currentRiskAssessment(userId:string):RiskAssessmentRecord{this.getUser(userId);const record=this.#riskAssessments.get(userId);if(record===undefined)throw new DomainError("RISK_ASSESSMENT_NOT_FOUND","A current risk assessment was not found",404);return record;}
  public recordLegalConsents(userId:string,input:Readonly<Record<string,unknown>>,sessionId:string,deviceId:string,acceptedAt:string):Readonly<Record<string,unknown>>{this.getUser(userId);const versions=validateLegalConsentVersions(input);const accepted:LegalConsentRecord[]=[];for(const[documentKey,documentVersion]of Object.entries(versions)){const key=`${userId}:${documentKey}:${documentVersion}`;let consent=this.#legalConsents.get(key);if(consent===undefined){consent=Object.freeze({id:randomUUID(),userId,documentKey,documentVersion,acceptedAt,sessionId,deviceId});this.#legalConsents.set(key,consent);}accepted.push(consent);}return Object.freeze({accepted:true,acceptedAt,consents:Object.freeze(accepted),allRequiredCurrentDocumentsAccepted:this.hasAllRequiredLegalConsents(userId)});}
  public legalDocuments(userId:string):readonly Readonly<Record<string,unknown>>[]{this.getUser(userId);return Object.freeze(LEGAL_DOCUMENTS.map((document)=>Object.freeze({id:document.key,title:LEGAL_DOCUMENT_TITLES[document.key]??document.key,version:document.version,productionApproved:document.productionApproved,required:document.required,contentURI:`https://demo.invalid/legal/${document.key}/${document.version}`,contentSHA256:"0".repeat(64),publishedAt:"2026-08-01T00:00:00.000Z"})));}
  public legalConsents(userId:string):readonly LegalConsentRecord[]{this.getUser(userId);return Object.freeze([...this.#legalConsents.values()].filter((record)=>record.userId===userId));}
  public hasAllRequiredLegalConsents(userId:string):boolean{this.getUser(userId);const planId=this.#subscriptionPlans.get(userId)??"equity";const optionsApply=PLANS.find((plan)=>plan.id===planId)?.features.optionsTrading??false;const adviserApplies=this.#eligibility.get(userId)?.adviserClientClassification==="adviser_client";return LEGAL_DOCUMENTS.filter((document)=>document.required||(document.key==="options"&&optionsApply)||(document.key==="advisory"&&adviserApplies)).every((document)=>this.#legalConsents.has(`${userId}:${document.key}:${document.version}`));}
  public subscription(userId:string):Readonly<Record<string,unknown>>{this.getUser(userId);const planId=this.#subscriptionPlans.get(userId)??"equity";const plan=PLANS.find((item)=>item.id===planId)!;return Object.freeze({status:"active",planId,productId:plan.productId,source:"verified_storekit",renewsAt:null});}
  public syncVerifiedSubscription(userId:string,transaction:VerifiedStoreKitTransaction):Readonly<Record<string,unknown>>{this.getUser(userId);const plan=PLANS.find((item)=>item.productId===transaction.productID);if(plan===undefined)throw new DomainError("SUBSCRIPTION_PRODUCT_UNKNOWN","Subscription product is not configured",400);this.#subscriptionPlans.set(userId,plan.id);return this.subscription(userId);}
  public entitledProductIds(userId:string):readonly string[]{const subscription=this.subscription(userId);return Object.freeze([String(subscription.productId)]);}
  public entitlements(userId:string):Entitlements{this.getUser(userId);const planId=this.#subscriptionPlans.get(userId)??"equity";const plan=PLANS.find((item)=>item.id===planId)!;return Object.freeze({...plan.features});}
  public riskPolicy(userId:string):RiskPolicy{this.getUser(userId);return this.#riskPolicies.get(userId)!;}
  public setRiskPolicy(userId:string,policy:RiskPolicy):RiskPolicy{this.getUser(userId);const current=this.#riskPolicies.get(userId)!;if(policy.policyId!==current.policyId||policy.version!==current.version+1)throw new DomainError("RISK_POLICY_VERSION_CONFLICT","The risk policy changed before this update could be applied",409);this.#riskPolicies.set(userId,policy);return policy;}
  public userAgents(userId:string):readonly UserAgentRecord[]{this.getUser(userId);return [...this.#agents.values()].filter((item)=>item.userId===userId);}
  public addUserAgent(userId:string,input:Readonly<Record<string,unknown>>,now:string):UserAgentRecord{this.getUser(userId);const agentId=typeof input.agentId==="string"?input.agentId:"";if(!AGENT_CATALOG.some((item)=>item.agentId===agentId))throw new DomainError("AGENT_NOT_FOUND","Agent definition was not found",404);const entitlements=this.entitlements(userId);if(!entitlements.agentCatalog.includes(agentId))throw new DomainError("AGENT_NOT_ENTITLED","Subscription does not include this agent version",403);const assignment=this.planAgentAssignment(userId,agentId);const definition=AGENT_CATALOG.find((item)=>item.agentId===agentId&&item.version===assignment.agentVersion);if(definition===undefined||!["paper","limited_rollout","live"].includes(definition.status))throw new DomainError("AGENT_VERSION_UNAVAILABLE","This agent has no implemented Paper runtime pipeline",409);if(this.userAgents(userId).length>=entitlements.maximumActiveAgents)throw new DomainError("AGENT_LIMIT_REACHED","Subscription active-agent limit reached",409);const allocation=input.allocation===undefined?0.1:input.allocation;if(typeof allocation!=="number"||!Number.isFinite(allocation)||allocation<=0||allocation>Math.min(0.8,this.riskPolicy(userId).maximumAccountAllocation))throw new DomainError("AGENT_ALLOCATION_INVALID","Agent allocation exceeds the effective risk policy",422);const approvalMode=input.approvalMode===undefined?"observe":input.approvalMode;if(approvalMode!=="observe"&&approvalMode!=="confirm_every_trade")throw new DomainError("AGENT_APPROVAL_MODE_INVALID","Paper agents support observe or confirm-every-trade approval",422);const configuration=validateAgentConfiguration(agentId,input.configuration);assertConfigurationResearchUniverse(configuration,assignment.researchUniverse,agentId);const record:UserAgentRecord={id:randomUUID(),userId,agentId,status:"paused",allocation,approvalMode,configurationVersion:1,configuration,createdAt:now,updatedAt:now};this.#agents.set(record.id,record);return record;}
  public patchUserAgent(userId:string,id:string,input:Readonly<Record<string,unknown>>,now:string):UserAgentRecord{const record=this.owned(this.#agents,userId,id,"USER_AGENT_NOT_FOUND");const assignment=this.planAgentAssignment(userId,record.agentId);const definition=AGENT_CATALOG.find((item)=>item.agentId===record.agentId&&item.version===assignment.agentVersion);if(definition===undefined||!["paper","limited_rollout","live"].includes(definition.status))throw new DomainError("AGENT_VERSION_UNAVAILABLE","The plan-mapped agent version has no enabled Demo runtime",409);let allocation=record.allocation;if(input.allocation!==undefined){if(typeof input.allocation!=="number"||!Number.isFinite(input.allocation)||input.allocation<=0||input.allocation>Math.min(0.8,this.riskPolicy(userId).maximumAccountAllocation))throw new DomainError("AGENT_ALLOCATION_INVALID","Agent allocation exceeds the effective risk policy",422);allocation=input.allocation;}let approvalMode=record.approvalMode;if(input.approvalMode!==undefined){if(input.approvalMode!=="observe"&&input.approvalMode!=="confirm_every_trade")throw new DomainError("AGENT_APPROVAL_MODE_INVALID","Paper agents support observe or confirm-every-trade approval",422);approvalMode=input.approvalMode;}if(input.configuration!==undefined&&(typeof input.configuration!=="object"||input.configuration===null||Array.isArray(input.configuration)))throw new DomainError("AGENT_CONFIGURATION_INVALID","Agent configuration must be an object",422);const configuration=validateAgentConfiguration(record.agentId,input.configuration===undefined?record.configuration:{...record.configuration,...input.configuration as Readonly<Record<string,unknown>>});assertConfigurationResearchUniverse(configuration,assignment.researchUniverse,record.agentId);record.allocation=allocation;record.approvalMode=approvalMode;if(input.configuration!==undefined){record.configuration=configuration;record.configurationVersion+=1;}record.updatedAt=now;return record;}
  public setAgentStatus(userId:string,id:string,status:"paused"|"monitoring",now:string):UserAgentRecord{const record=this.owned(this.#agents,userId,id,"USER_AGENT_NOT_FOUND");if(status==="monitoring"){const entitlements=this.entitlements(userId);if(this.userAgents(userId).length>entitlements.maximumActiveAgents)throw new DomainError("AGENT_LIMIT_REACHED","The account has more assigned agents than the current subscription permits",409);const assignment=this.planAgentAssignment(userId,record.agentId);const definition=AGENT_CATALOG.find((item)=>item.agentId===record.agentId&&item.version===assignment.agentVersion);if(definition===undefined||!["paper","limited_rollout","live"].includes(definition.status))throw new DomainError("AGENT_VERSION_UNAVAILABLE","The plan-mapped agent version has no enabled Demo runtime",409);const configuration=validateAgentConfiguration(record.agentId,record.configuration);assertConfigurationResearchUniverse(configuration,assignment.researchUniverse,record.agentId);}record.status=status;record.updatedAt=now;return record;}
  public deleteUserAgent(userId:string,id:string,_now:string):void{this.owned(this.#agents,userId,id,"USER_AGENT_NOT_FOUND");this.#agents.delete(id);}
  public proposals(userId:string):readonly ProposalRecord[]{return [...this.#proposals.values()].filter((item)=>item.userId===userId);}
  public proposal(userId:string,id:string):ProposalRecord{return this.owned(this.#proposals,userId,id,"PROPOSAL_NOT_FOUND");}
  public proposalAction(userId:string,id:string,status:"APPROVED"|"USER_REJECTED",now:string):ProposalRecord{const record=this.proposal(userId,id);if(record.status!=="AWAITING_USER_APPROVAL")throw new DomainError("PROPOSAL_NOT_ACTIONABLE","Proposal is no longer actionable",409);if(Date.parse(record.proposal.expirationTimestamp)<=Date.parse(now)){record.status="EXPIRED";throw new DomainError("PROPOSAL_EXPIRED","Proposal has expired",409);}record.status=status;record.updatedAt=now;return record;}
  public approveProposal(userId:string,id:string,verification:VerifiedStepUpAuthentication,idempotencyKey:string,approvedAt:string):ProposalRecord{this.requireEligible(userId);this.currentRiskAssessment(userId);if(!this.hasAllRequiredLegalConsents(userId))throw new DomainError("LEGAL_CONSENTS_REQUIRED","Every required current legal-document version must be accepted before a proposal can be approved",409);const proposal=this.proposalAction(userId,id,"APPROVED",approvedAt);const approval:ApprovalRecord=Object.freeze({id:randomUUID(),userId,proposalId:id,status:"approved",approvingDeviceId:verification.deviceId,sessionId:verification.sessionId,authenticationMethod:verification.method,authenticationVerificationId:verification.verificationId,authenticatedAt:verification.authenticatedAt,approvedAt,idempotencyKey});this.#approvals.set(id,approval);return proposal;}
  public approvalForProposal(userId:string,proposalId:string):ApprovalRecord{this.proposal(userId,proposalId);const approval=this.#approvals.get(proposalId);if(approval===undefined||approval.userId!==userId)throw new DomainError("APPROVAL_NOT_FOUND","Proposal approval was not found",404);return approval;}
  public orders(userId:string):readonly OrderRecord[]{return [...this.#orders.values()].filter((item)=>item.userId===userId);}
  public order(userId:string,id:string):OrderRecord{return this.owned(this.#orders,userId,id,"ORDER_NOT_FOUND");}
  public cancelOrder(userId:string,id:string,now:string):OrderRecord{const record=this.order(userId,id);if(!["PENDING","SUBMITTED","PARTIALLY_FILLED"].includes(record.status))throw new DomainError("ORDER_NOT_CANCELABLE","A terminal Demo order cannot be canceled",409);const canceled=Object.freeze({...record,status:"CANCELED",terminalAt:now,statusReason:"Canceled by the authenticated Demo user.",reconciliationStatus:"reconciled",auditTimeline:Object.freeze([...record.auditTimeline,{status:"CANCELED",occurredAt:now,reasonCode:"USER_CANCELED_DEMO_ORDER"}]),updatedAt:now});this.#orders.set(id,canceled);return canceled;}
  public notifications(userId:string):readonly NotificationRecord[]{return [...this.#notifications.values()].filter((item)=>item.userId===userId);}
  public readNotification(userId:string,id:string,now:string):NotificationRecord{const record=this.owned(this.#notifications,userId,id,"NOTIFICATION_NOT_FOUND");record.readAt=now;return record;}
  public pauseAll(userId:string,now:string):Readonly<Record<string,unknown>>{for(const agent of this.userAgents(userId)){agent.status="paused";agent.updatedAt=now;}for(const proposal of this.proposals(userId))if(["DRAFT","ANALYZED","SCHEMA_VALIDATED","RISK_CHECKED","BROKER_REVIEWED","AWAITING_USER_APPROVAL"].includes(proposal.status)){proposal.status="CANCELED";proposal.updatedAt=now;}return Object.freeze({paused:true,occurredAt:now,positionsUntouched:true});}
  public resumeAll(userId:string,now:string):Readonly<Record<string,unknown>>{const agents=this.userAgents(userId);if(agents.length>this.entitlements(userId).maximumActiveAgents)throw new DomainError("AGENT_LIMIT_REACHED","The account has more assigned agents than the current subscription permits",409);for(const agent of agents){const assignment=this.planAgentAssignment(userId,agent.agentId);const definition=AGENT_CATALOG.find((item)=>item.agentId===agent.agentId&&item.version===assignment.agentVersion);if(definition===undefined||!["paper","limited_rollout","live"].includes(definition.status))throw new DomainError("AGENT_VERSION_UNAVAILABLE","A plan-mapped agent version has no enabled Demo runtime",409,{agentId:agent.id});const configuration=validateAgentConfiguration(agent.agentId,agent.configuration);assertConfigurationResearchUniverse(configuration,assignment.researchUniverse,agent.agentId);}for(const agent of agents){agent.status="monitoring";agent.updatedAt=now;}return Object.freeze({resumed:true,occurredAt:now,positionsUntouched:true});}
  public idempotent<T>(userId:string,key:string,payload:unknown,operation:()=>T):T{const scope=`${userId}:${key}`;const fingerprint=JSON.stringify(payload);const prior=this.#idempotency.get(scope);if(prior!==undefined){if(prior.fingerprint!==fingerprint)throw new DomainError("IDEMPOTENCY_KEY_REUSED","Idempotency key was reused with a different payload",409);return prior.value as T;}const value=operation();this.#idempotency.set(scope,{fingerprint,value});return value;}
  public async idempotentAsync<T>(userId:string,key:string,payload:unknown,operation:()=>Promise<T>):Promise<T>{const scope=`${userId}:${key}`;const fingerprint=JSON.stringify(payload);const prior=this.#idempotency.get(scope);if(prior!==undefined){if(prior.fingerprint!==fingerprint)throw new DomainError("IDEMPOTENCY_KEY_REUSED","Idempotency key was reused with a different payload",409);return await prior.value as T;}const pending=operation();this.#idempotency.set(scope,{fingerprint,value:pending});try{return await pending;}catch(error){if(this.#idempotency.get(scope)?.value===pending)this.#idempotency.delete(scope);throw error;}}
  public createSupportTicket(userId:string,input:Readonly<Record<string,unknown>>,now:string):Readonly<Record<string,unknown>>{this.getUser(userId);const ticket=Object.freeze({id:randomUUID(),status:"open",subject:String(input.subject??"Support request").slice(0,200),createdAt:now});this.#supportTickets.set(String(ticket.id),ticket);return ticket;}
  public closeAccount(userId:string):Readonly<Record<string,unknown>>{const user=this.getUser(userId);if(this.orders(userId).some((item)=>!["FILLED","CANCELED","REJECTED"].includes(item.status)))throw new DomainError("OPEN_ORDERS_EXIST","Cancel or resolve open orders before deleting the account",409);user.accountMode="demo";return Object.freeze({deletionRequested:true,brokerRevocationPending:false,retentionNotice:"Records subject to legal retention are preserved and access is restricted."});}
  public plans():readonly SubscriptionPlanCatalog[]{return PLANS;}
  public dashboard(userId:string):Readonly<Record<string,unknown>>{return demoDashboard(this,userId);}
  public portfolio(userId:string):Readonly<Record<string,unknown>>{this.getUser(userId);return demoPortfolio();}
  public portfolioHistory(userId:string):Readonly<Record<string,unknown>>{this.getUser(userId);return Object.freeze({mode:"demo",range:"1M",data:[{timestamp:"2026-07-01T20:00:00Z",value:12000},{timestamp:"2026-08-01T14:00:00Z",value:12430}],benchmark:null});}
  public positions(userId:string):readonly Readonly<Record<string,unknown>>[]{this.getUser(userId);return demoPortfolio().positions as readonly Readonly<Record<string,unknown>>[];}
  public position(userId:string,id:string):Readonly<Record<string,unknown>>{const value=this.positions(userId).find((item)=>item.id===id);if(value===undefined)throw new DomainError("POSITION_NOT_FOUND","Position was not found",404);return value;}
  public performance(userId:string):Readonly<Record<string,unknown>>{this.getUser(userId);return Object.freeze({classification:"demo",dateRange:"1M",grossOrNet:"net_of_paper_assumptions",return:0.0358,maximumDrawdown:0.022,volatility:0.14,benchmark:null,methodology:"Demo fixture only; deposits and withdrawals excluded."});}
  public agentRuns(userId:string,id:string):readonly Readonly<Record<string,unknown>>[]{this.userAgents(userId).find((item)=>item.id===id)??(()=>{throw new DomainError("USER_AGENT_NOT_FOUND","Agent was not found",404);})();return Object.freeze([{id:"demo-run-1",startedAt:"2026-08-01T13:59:00Z",completedAt:"2026-08-01T14:00:00Z",outcome:"proposal_created",modelVersion:null,deterministicStrategyVersion:"foundation-equity-rules-1.0.0"}]);}
  public riskEvents(userId:string):readonly Readonly<Record<string,unknown>>[]{this.getUser(userId);return Object.freeze([{id:"demo-risk-event",type:"daily_loss_warning",severity:"warning",mode:"demo",occurredAt:"2026-08-01T14:00:00Z",reason:"Demo threshold approaching"}]);}
  public brokerConnection(userId:string):Readonly<Record<string,unknown>>{this.getUser(userId);return Object.freeze({status:"connected",maskedAccountIdentifier:"Demo Agentic account •••• 2841",capabilities:["demo_portfolio"],equityTradingAvailable:false,optionsTradingAvailable:false});}
  public activity(userId:string):readonly (ProposalRecord|OrderRecord)[]{return Object.freeze([...this.proposals(userId),...this.orders(userId)].sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)));}
  public settings(userId:string):Readonly<Record<string,unknown>>{const account=this.getUser(userId);return this.#settings.get(userId)??Object.freeze({privacyMode:false,appearance:"system",notificationPreviews:"private",notificationPreferences:{detailedPreviewsEnabled:false,criticalNotificationsEnabled:false},accountMode:account.accountMode});}
  public patchSettings(userId:string,input:Readonly<Record<string,unknown>>,now:string):Readonly<Record<string,unknown>>{const value=Object.freeze({...this.settings(userId),...input,accountMode:this.getUser(userId).accountMode,updatedAt:now});this.#settings.set(userId,value);return value;}
  public registerPushToken(userId:string,_input:Readonly<Record<string,unknown>>):Readonly<Record<string,unknown>>{this.getUser(userId);return Object.freeze({registered:true,environment:"demo",detailsStored:false});}
  public unregisterPushToken(userId:string,_deviceId:string):Readonly<Record<string,unknown>>{this.getUser(userId);return Object.freeze({unregistered:true});}
  public dataExportStatus(userId:string):Readonly<Record<string,unknown>>{this.getUser(userId);return Object.freeze({status:"not_requested"});}
  public requestDataExport(userId:string,_input:Readonly<Record<string,unknown>>,now:string):Readonly<Record<string,unknown>>{this.getUser(userId);return Object.freeze({requestId:randomUUID(),status:"queued",requestedAt:now});}
  public healthy():boolean{return true;}
  private planAgentAssignment(userId:string,agentId:string):PlanAgentAssignment{const planId=this.#subscriptionPlans.get(userId)??"equity";const assignment=PLANS.find((plan)=>plan.id===planId)?.agents.find((item)=>item.agentId===agentId);if(assignment===undefined)throw new DomainError("AGENT_NOT_ENTITLED","The current plan does not include this exact agent assignment",403);return assignment;}
  private owned<T extends{readonly userId:string}>(map:Map<string,T>,userId:string,id:string,code:string):T{const value=map.get(id);if(value===undefined||value.userId!==userId)throw new DomainError(code,"Resource was not found",404);return value;}
}

export type Awaitable<T>=T|Promise<T>;
export interface ApiDataStore {
  readonly persistenceKind:"ephemeral"|"persistent";
  userForAppleSubject(subject:string,email?:string,displayName?:string):Awaitable<UserRecord>;
  consumeAppleIdentityAssertion(assertionDigest:string,expiresAt:string,consumedAt:string):Awaitable<void>;
  consumeStepUpAuthentication(userId:string,verification:VerifiedStepUpAuthentication,usedAt:string):Awaitable<void>;
  getUser(userId:string):Awaitable<UserRecord>;
  patchUser(userId:string,input:Readonly<Record<string,unknown>>):Awaitable<UserRecord>;
  onboarding(userId:string):Awaitable<Readonly<Record<string,unknown>>>;
  updateOnboarding(userId:string,step:number):Awaitable<Readonly<Record<string,unknown>>>;
  eligibility(userId:string):Awaitable<EligibilityRecord|undefined>;
  recordEligibility(userId:string,input:Readonly<Record<string,unknown>>,recordedAt:string):Awaitable<EligibilityRecord>;
  requireEligible(userId:string):Awaitable<EligibilityRecord>;
  createRiskAssessment(userId:string,input:Readonly<Record<string,unknown>>,recordedAt:string):Awaitable<RiskAssessmentRecord>;
  currentRiskAssessment(userId:string):Awaitable<RiskAssessmentRecord>;
  recordLegalConsents(userId:string,input:Readonly<Record<string,unknown>>,sessionId:string,deviceId:string,acceptedAt:string):Awaitable<Readonly<Record<string,unknown>>>;
  legalDocuments(userId:string):Awaitable<readonly Readonly<Record<string,unknown>>[]>;
  legalConsents(userId:string):Awaitable<readonly LegalConsentRecord[]>;
  hasAllRequiredLegalConsents(userId:string):Awaitable<boolean>;
  plans(userId?:string):Awaitable<readonly SubscriptionPlanCatalog[]>;
  subscription(userId:string):Awaitable<Readonly<Record<string,unknown>>>;
  syncVerifiedSubscription(userId:string,transaction:VerifiedStoreKitTransaction):Awaitable<Readonly<Record<string,unknown>>>;
  entitledProductIds(userId:string):Awaitable<readonly string[]>;
  entitlements(userId:string):Awaitable<Entitlements>;
  riskPolicy(userId:string):Awaitable<RiskPolicy>;
  setRiskPolicy(userId:string,policy:RiskPolicy):Awaitable<RiskPolicy>;
  userAgents(userId:string):Awaitable<readonly UserAgentRecord[]>;
  addUserAgent(userId:string,input:Readonly<Record<string,unknown>>,now:string):Awaitable<UserAgentRecord>;
  patchUserAgent(userId:string,id:string,input:Readonly<Record<string,unknown>>,now:string):Awaitable<UserAgentRecord>;
  setAgentStatus(userId:string,id:string,status:"paused"|"monitoring",now:string):Awaitable<UserAgentRecord>;
  deleteUserAgent(userId:string,id:string,now:string):Awaitable<void>;
  proposals(userId:string):Awaitable<readonly ProposalRecord[]>;
  proposal(userId:string,id:string):Awaitable<ProposalRecord>;
  proposalAction(userId:string,id:string,status:"APPROVED"|"USER_REJECTED",now:string):Awaitable<ProposalRecord>;
  approveProposal(userId:string,id:string,verification:VerifiedStepUpAuthentication,idempotencyKey:string,approvedAt:string):Awaitable<ProposalRecord>;
  approvalForProposal(userId:string,proposalId:string):Awaitable<ApprovalRecord>;
  orders(userId:string):Awaitable<readonly OrderRecord[]>;
  order(userId:string,id:string):Awaitable<OrderRecord>;
  cancelOrder(userId:string,id:string,now:string):Awaitable<OrderRecord>;
  notifications(userId:string):Awaitable<readonly NotificationRecord[]>;
  readNotification(userId:string,id:string,now:string):Awaitable<NotificationRecord>;
  pauseAll(userId:string,now:string):Awaitable<Readonly<Record<string,unknown>>>;
  resumeAll(userId:string,now:string):Awaitable<Readonly<Record<string,unknown>>>;
  idempotentAsync<T>(userId:string,key:string,payload:unknown,operation:()=>Promise<T>):Promise<T>;
  createSupportTicket(userId:string,input:Readonly<Record<string,unknown>>,now:string):Awaitable<Readonly<Record<string,unknown>>>;
  closeAccount(userId:string):Awaitable<Readonly<Record<string,unknown>>>;
  dashboard(userId:string):Awaitable<Readonly<Record<string,unknown>>>;
  portfolio(userId:string):Awaitable<Readonly<Record<string,unknown>>>;
  portfolioHistory(userId:string):Awaitable<Readonly<Record<string,unknown>>>;
  positions(userId:string):Awaitable<readonly Readonly<Record<string,unknown>>[]>;
  position(userId:string,id:string):Awaitable<Readonly<Record<string,unknown>>>;
  performance(userId:string):Awaitable<Readonly<Record<string,unknown>>>;
  agentRuns(userId:string,id:string):Awaitable<readonly Readonly<Record<string,unknown>>[]>;
  riskEvents(userId:string):Awaitable<readonly Readonly<Record<string,unknown>>[]>;
  brokerConnection(userId:string):Awaitable<Readonly<Record<string,unknown>>>;
  activity(userId:string):Awaitable<readonly (ProposalRecord|OrderRecord)[]>;
  settings(userId:string):Awaitable<Readonly<Record<string,unknown>>>;
  patchSettings(userId:string,input:Readonly<Record<string,unknown>>,now:string):Awaitable<Readonly<Record<string,unknown>>>;
  registerPushToken(userId:string,input:Readonly<Record<string,unknown>>):Awaitable<Readonly<Record<string,unknown>>>;
  unregisterPushToken(userId:string,deviceId:string):Awaitable<Readonly<Record<string,unknown>>>;
  dataExportStatus(userId:string):Awaitable<Readonly<Record<string,unknown>>>;
  requestDataExport(userId:string,input:Readonly<Record<string,unknown>>,now:string):Awaitable<Readonly<Record<string,unknown>>>;
  healthy():Awaitable<boolean>;
}

export function demoDashboard(store:MemoryDataStore,userId:string):Readonly<Record<string,unknown>>{store.getUser(userId);const proposals=store.proposals(userId);return Object.freeze({mode:"demo",dataClassification:"demo",portfolio:{value:12430,todayChange:-120,todayChangePercent:-0.0096,asOf:FIXTURE_NOW,dataClassification:"demo"},agentStatus:{activeAgents:store.userAgents(userId),pendingProposals:proposals.filter((item)=>item.status==="AWAITING_USER_APPROVAL").length,riskState:"within_limits",connectionHealth:"demo_connected"},risk:{dailyLossUsed:120,dailyLossLimit:store.riskPolicy(userId).maximumDailyLoss,allocationUsed:0.32,buyingPowerReserve:0.42},positions:[{id:"position-demo-aapl",symbol:"AAPL",instrumentType:"equity",quantity:5,marketValue:1000,todayChange:-12,totalReturn:80,dataClassification:"demo"}],recentActivity:proposals.slice(0,5).map((proposal)=>({type:"proposal",id:proposal.id,status:proposal.status,mode:"demo",dataClassification:"demo",occurredAt:proposal.updatedAt}))});}
export function demoPortfolio():Readonly<Record<string,unknown>>{return Object.freeze({accountId:DEMO_ACCOUNT_ID,mode:"demo",asOf:FIXTURE_NOW,totalValue:12430,cash:5230,positions:[{id:"position-demo-aapl",symbol:"AAPL",companyName:"Apple Inc.",instrumentType:"equity",quantity:5,averageCost:184,marketValue:1000,todayPnl:-12,unrealizedPnl:80,dataClassification:"demo"},{id:"position-demo-option",symbol:"SPY",instrumentType:"option",strategy:"protective_put",quantity:1,expiration:"2026-09-18",maximumLoss:250,dataClassification:"demo"}]});}

const asObject=(value:unknown):Readonly<Record<string,unknown>>=>typeof value==="object"&&value!==null&&!Array.isArray(value)?value as Readonly<Record<string,unknown>>:{};
const AGENT_SYMBOL_PATTERN=/^[A-Z][A-Z0-9.-]{0,14}$/;
function assertConfigurationResearchUniverse(configuration:Readonly<Record<string,unknown>>,researchUniverse:readonly string[],agentId:string):void{const symbol=configuration.symbol;if(symbol!==undefined&&(typeof symbol!=="string"||!researchUniverse.includes(symbol)))throw new DomainError("AGENT_SYMBOL_NOT_ALLOWED","The configured symbol is not available for this exact plan agent assignment",409,{agentId});}
function validateAgentConfiguration(agentId:string,value:unknown):Readonly<Record<string,unknown>>{const configuration=asObject(value);if(agentId==="foundation-equity"){const symbol=typeof configuration.symbol==="string"?configuration.symbol.trim().toUpperCase():"";const targetOrderAmount=configuration.targetOrderAmount;if(!AGENT_SYMBOL_PATTERN.test(symbol)||typeof targetOrderAmount!=="number"||!Number.isFinite(targetOrderAmount)||targetOrderAmount<=0)throw new DomainError("AGENT_CONFIGURATION_INVALID","Foundation Equity requires a valid symbol and positive targetOrderAmount",422);return Object.freeze({...configuration,symbol,targetOrderAmount});}if(Object.keys(configuration).length===0)throw new DomainError("AGENT_CONFIGURATION_INVALID","An agent configuration is required",422);return Object.freeze({...configuration});}
